- manual/References.md
> add nano install reference

- manual/1.0-SettingUpVirtualBox.md
Clean up steps about setting up host-only network
> Fix formatting, clarify multiple network situation

- README.md
- client_files/php.sh
This adds to the PHP script to generate info.php and prompts the user to verify PHP successfully executes upon completion.
> mod php.sh to create info.php, revise readme

- README.md
This pull request adds some simple documentation about the optional mediawiki-quick.sh script.
> documentation for mediawiki-quick.sh

- README.md
- client_files/mediawiki-quick.sh
- client_files/mysql.sh
- client_files/php.sh
- client_files/yums.sh
This pull request adds user prompts instead of adding parameters after the name of the script. The readme is updated to reflect these changes. I tested all but mysql.sh, but it would be best if you could also test these.
> Add user prompts

- client_files/install.sh
- client_files/mediawiki-quick.sh
- client_files/mysql.sh
- client_files/php.sh
- client_files/yums.sh
This pull request addresses the following issues:
- #32 Make shell scripts optionally have parameters
- #33 Make single install script that installs everything
- #34 Make php.sh update PATH immediately
This PR was originally just focused on #32, but this was closely related to the others so they were brought into scope.
> Create single-file install

- client_files/import-wiki.sh
File takes a SQL file and a .tar.gz of a wiki's images directory and imports it into Meza1.
> Add import-wiki.sh script to import an existing wiki

- README.md
- client_files/install.sh
> Bump to v0.2

- client_files/ExtensionSettings.php
Adds the Pipe Escape extension to ExtensionSettings.php.
> Add pipe escape extension

- client_files/vmsetupwin.bat
You should be able to use this with your own windows pc now. It takes 2 parameters: iso file path and virtual machine name. 2 prompts to follow.
Let me know what you think.
I'll start working on a bash version.
> Added new vm setup batch file

- README.md
- manual/1.0-SettingUpVirtualBoxWindows.md
Since on Windows we now have a Virtual Box setup script the install steps are slightly different. This PR will include the different procedure and update the main README file to reference it.
Every effort should be made to make a universal bash script which can be run with git-bash on Windows so we don't have multiple different documentation sources.
Additionally, this manual procedure should be considered in future work to improve scripting. We should aim to reduce this down to as few steps as possible.
> Windows-specific Vbox setup with scripted install

- manual/2.1-CreateCloneVMs.md
This PR adds a manual page with steps for creating a clone of a VM.
> Add instructions for creating VM clones

- README.md
Forgot to bump version number after v0.4 milestone and release.
> Bump version number in README.md to v0.4

- CONTRIBUTING.md
- README.md
This pull request adds a contributing guide, which also includes information on how to test meza. No testing is required for this PR. Please feel free to add tests or other improvements.
Closes #202
> Add contributing guide and test requirements

- scripts/install.sh
Closes #238.
The logic now progresses through four possible values of network adapters, looking if those names are found in the output of `ip addr`. If the name is found, it sets the default mw_api_domain to that adapter's IP address. This is the best approach I could find since I don't know how to determine which (of many) network adapters is used for serving. These are ordered so the most-likely-correct adapter is last (since this method overwrites previous values, if found).
To close #238, I added an if statement when prompting the user for the domain. Now it only suggests a value if the default value was set. For some reason, if the variable has no value and is displayed as a default suggestion, it doesn't work right when used later in subsequent scripts (even when the user changes …
> change logic to find domain; fix case for value not found

- README.md
- manual/ElasticsearchPlugins.md
In #315 I forgot to add docs for Elasticsearch plugins. They are added in this pull request.
> Add docs for elasticsearch plugins

- .github/ISSUE_TEMPLATE.md
For issues, it is (sometimes) useful to have the environment details. This will help us remember to add those details when relevant.
> add environment details

- config/core/LocalSettings.php
Use specific version of SemanticForms, rather than using REL1_25 branch.
* Closes #370
> Use SemanticForms version 3.5

- scripts/install.sh
Make sure firewalld is installed at the beginning of install.
> Make sure firewalld is installed

- config/core/LocalSettings.php
Add Extension:Data Transfer to meza.
> add Extension:Data Transfer

- config/template/more-extensions.php
A description of the pull request
> added TCHB namespace and CollapsibleSections ext

- scripts/install.sh
- scripts/yums.sh
Merge these PRs from master into this branch so builds don't fail:
* #426: EPEL-fix
* #419: SMW-fix
* #414: Install firewall after prompts
> Pulling EPEL-fix, SMW-fix and delay-fire-install from master

- README.md
Add expected install time (20-45 minutes) to README
> Specify expected time to install meza

- manual/1.0-SettingUpVirtualBox.md
Add a little instruction on how to configure partition allocation upon VM creation.
* Addresses #420
> Docs - add steps for partition allocations

- scripts/meza.sh
Make the command `meza setup dev` run the `setup-dev.sh` script such that it's easy to setup FTP and Git users.
> Make meza command for setting up dev (ftp, git)

- README.md
> Add GIF to README, improve intro words

- README.md
- manual/1.0-SettingUpVirtualBox.md
To README.md:
* Add TOC
* Improve/clarify wording
* Add list of stuff installed (services, extensions)
* Remove Vbox steps (just link to Vbox readme)
To Vbox readme:
* Add tl;dr
* Fix some bad steps
> README updates

- ansible/roles/mediawiki/templates/LocalSettings.php.j2
check for existing postLocalSettings_allWikis file had incorrect path.
> Correcting LocalSettings file path 

- README.md
- manual/1.0-SettingUpVirtualBox.md
- src/scripts/getmeza.sh
Documentation fixes
N/A
* README.md
* manual/1.0-SettingUpVirtualBox.md
* scr/scripts/getmeza.sh
* Closes #501
> Command updates - Install to Setup/Deploy

- src/roles/init-controller-config/tasks/main.yml
> Remove bad owner/group/mode from Ansible synchronize (rsync)

- src/roles/mediawiki/tasks/main.yml
Security release just made per mailing list: https://lists.gt.net/wiki/wikitech/798026
> Bump to MW 1.27.2 security release

- .travis.yml
> Reduce complexity of env vars in Travis

- src/roles/mediawiki/templates/LocalSettings.php.j2
Fix mismatched variable names.
> Fix mismatched variable names

- src/roles/apache-php/tasks/php.yml
Addresses #597.
Not sure yet if this will close the above issue.
Other changes: Standardization and cleanup of `php.yml`
> Add PEAR Net_SMTP

- config/core/defaults.yml
- src/roles/set-vars/tasks/main.yml
- src/scripts/meza.py
> Call it defaults.yml not paths.yml

- manual/AddingWikis.md
- src/roles/apache-php/templates/httpd.conf.j2
- src/roles/mediawiki/templates/BlenderSettings.php.j2
- src/roles/mediawiki/templates/LocalSettings.php.j2
- src/scripts/unifyUserTables.php
* Closes #626: Fix primewiki discrepancies
* Closes #627: Fix apache logging
* Closes #631: Use logio module values
> fix prime_wiki; fix httpd logging

- config/core/MezaCoreExtensions.yml
With SemanticMediaWiki/SemanticMediaWiki#2433, specify SMW 2.5.2
Closes #636
> Specify SMW v2.5.2 

- src/roles/database/tasks/secure-installation.yml
- src/scripts/meza.py
> fix always_run; add git commit to meza --version

- config/core/defaults.yml
- manual/DirectoryStructure.md
- src/playbooks/site.yml
- src/roles/base/tasks/main.yml
- src/roles/cron/tasks/main.yml
- src/roles/grant-keys/tasks/main.yml
- src/roles/haproxy/tasks/main.yml
- src/roles/nodejs/tasks/main.yml
- src/roles/parsoid/tasks/main.yml
- src/roles/revoke-keys/tasks/main.yml
- src/roles/verify-wiki/tasks/main.yml
- src/scripts/getmeza.sh
- src/scripts/meza.py
- src/scripts/shell-functions/linux-user.sh
- src/scripts/ssh-users/setup-master-user.sh
- src/scripts/ssh-users/setup-minion-user.sh
- tests/deploys/setup-alt-source-backup.yml
- tests/docker/import-from-alt-remote.setup.sh
- tests/docker/init-controller.sh
- tests/docker/init-minion.sh
> Don't use /home for meza-generated users

- manual/DirectoryStructure.md
Directory structure document should point to issues with files.
Refs:
* issue #625
* issue #662
* issue #735
> Add FIXME and issue ref to note about change required

- CONTRIBUTING.md
- README.md
- manual/SettingUpVirtualBox.md
- src/scripts/meza.py
Issues:
* Closes #734: Fix suggestion at end of `meza setup env`
* Closes #691: Remove `getmeza.org`, use `git clone`
* Closes #557: Document how to debug (in CONTRIBUTING)
* Closes #533: Add Demo Wiki Admin user password
> Misc documentation fixes

- src/scripts/meza.py
> Fix suggestion at end of meza setup env for dev branch

- src/scripts/getmeza.sh
- src/scripts/ssh-users/setup-minion-user.sh
> Don't require TTY or visible password for sudo. 

- src/roles/base/tasks/main.yml
Need to specify the location for new user home directories for minions. Not required for controller since `site.yml` handles controller already.
> Need to force move home on minions

- config/core/MezaCoreExtensions.yml
- config/core/defaults.yml
- src/roles/apache-php/templates/httpd.conf.j2
- src/roles/base/tasks/main.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/mediawiki/templates/elastic-rebuild-all.sh.j2
- src/roles/mediawiki/templates/smw-rebuild-all.sh.j2
* dce306d: Add Extension:DisplayTitle (Closes #779)
* 14154d2: Specify ServerName (Closes #13)
* 4e675aa: Remove default international phonetic alphabet selector (Closes #716)
* a12841f: Give search-index and smw-data logs their own directories (Closes #774)
> Miscellaneous changes in support of v1.0

- src/roles/base/tasks/main.yml
> Allow adding custom CA certs

- src/roles/database/defaults/main.yml
> Only keep MariaDB binary logs for 2 days

- README.md
- manual/multi-server.md
These need significant improvement, but it's a start.
> Add multi-server docs

- config/core/defaults.yml
- src/roles/elasticsearch/defaults/main.yml
- src/roles/elasticsearch/templates/elasticsearch.repo.j2
- src/roles/elasticsearch/templates/elasticsearch.yml.j2
* Set version in `defaults.yml`
* Fix https in repo URLs (ES 2.x cares)
* Make `elasticsearch.yml` support 2.x-style dynamic scripting config
> Modify Elasticsearch setup to be easy to upgrade

- README.md
- manual/PerformanceMonitoring.md
Create documentation of performance monitoring features, PerformanceMonitoring.md, and add reference in README.md.
> Create documentation for performance monitoring

- src/roles/remote-mysqldump/tasks/main.yml
> Fix create wiki when using a database-source for imports

- src/playbooks/delete-wiki-promptless.yml
- src/playbooks/delete-wiki.yml
- src/roles/delete-wiki-wrapper/tasks/main.yml
- src/scripts/meza.py
- tests/deploys/import-from-remote.controller.sh
- tests/docker/import-from-remote.setup.sh
Closes #206 
Do `sudo meza delete wiki <environment>` or `sudo meza delete wiki-promptless <environment> <wiki_id>`.
> Add `meza delete wiki`

- manual/ElasticsearchPlugins.md
Minor correction; and link URL
> minor updates to ElasticsearchPlugins.md

- src/roles/remote-mysqldump/tasks/main.yml
- src/roles/update.php/tasks/main.yml
- src/roles/verify-wiki/tasks/import-wiki-sql.yml
Needed `import_role` in several places
> Wasn't passing wiki_id into update.php, updating same wiki many times

- config/core/defaults.yml
- src/playbooks/cleanup-upload-stash.yml
- src/roles/cron/templates/meza-ansible.crontab.j2
- src/scripts/meza.py
* Add `sudo meza maint cleanuploadstash <environment name>` (add command to `meza.py` and create playbook `cleanup-upload-stash.yml` to do the work)
* Add daily run to user meza-ansible's crontab
* Add default cron time to `defaults.yml`
Closes #497
> Cleanup upload stash (temp upload files)

- src/roles/apache-php/tasks/php.yml
- src/roles/apache-php/templates/freetds.conf.j2
- src/roles/base/tasks/main.yml
Add `php56u-mssql` package in order to talk to Microsoft SQL Server databases. Add FreeTDS config to fix unicode issues.
Also added some "latest" tags to an unrelated file because I already had them in my working directory and they pretty minor additions.
> Add PHP MSSQL package & necessary FreeTDS config

- manual/commands.md
- manual/installing-additional-extensions.md
- manual/multi-server.md
This documents the `meza --help` options.
I closed https://github.com/enterprisemediawiki/meza/pull/917 
Hopefully I skipped Travis with the [ci skip] token in the commit message.
> Adds a reference for Meza commands

- manual/README.md
Incorporated James' words https://github.com/enterprisemediawiki/meza/issues/692 to close that issue.
This should go in with the [pull requesst for commands.md](https://github.com/enterprisemediawiki/meza/pull/924)
> Create README in the manual folder

- src/scripts/importExtensions.php
This script takes a single argument: the API URL of the non-Meza wiki, to read information about what extensions exist in the "foreign" wiki.  The script reads information from both MezaCoreExtensions.yml and MezaLocalExtensions.yml (so it must be run from a Meza control host).  The script outputs a list of what is currently not included in either Core, or Local - providing you with a list of what you need to add to MezaLocalExtensions.yml in order to fully support an import of the foreign wiki.
Example: `php src/scripts/importExtensions.php https://wikipedia.org/w/api.php` shows what you need to do to make Meza support wikipedia.org.
The output of the example above is: 
```
php src/scripts/importExtensions.php https://wikipedia.org/w/api.php
Here are the extensions in core
AdminLinks …
```
> add script to identify missing extensions for a new wiki import

- config/core/ansible.cfg
- manual/LowMemory.md
1. Adds comment about "forks" option in Ansible to config file
1. Adds new documentation file for Low Memory environments
> Doc possible ansible cfg option in low RAM <=2GB environments

- config/core/defaults.yml
> Bump MW 1.27.2 to 1.27.4 for security release

- manual/LowMemory.md
Adding more help for people trying Meza in an environment which may only have 2GB (like a VM)
> more comments on Low Memory environments

- src/roles/mediawiki/tasks/main.yml
Adds following tags:
- git-extensions
- git-core-extensions
- latest
Closes #946.
> Add tags to loading local and core extension yml files

- src/roles/base/tasks/main.yml
> Install rsync if it isn't already

- src/roles/mediawiki/templates/LocalSettings.php.j2
> Fix created LocalSettings.php for those with OCD

- src/roles/mediawiki/tasks/main.yml
> Provide a way to check out private repositories

- src/scripts/meza.py
* Adds `sudo meza update` command
* Closes #568 
> Add 'meza update' command

- src/scripts/meza.py
Several fixes for `meza update`. 
* Wasn't working on remote branches (e.g. `31.x` not created, but `origin/31.x` exists)
* Needed to change working directory in `meza.py` else got different results based upon shell working directory
None
> Fix several issues with 'meza update'

- src/roles/base/templates/config.php.j2
- src/roles/base/templates/config.sh.j2
- src/scripts/merge-pages/Main_Page.mediawiki
- src/scripts/unite-the-wikis.sh
- src/scripts/uniteTheWikis.php
Merge many wikis into one wiki. See `mergify.sh` and `slack-notify.sh` examples below.
```bash
#!/bin/sh
#
CHANNEL="some-channel"
TOKEN="some/slack/token"
USERNAME="Some username"
MESSAGE="Starting mergify.sh on my server"
COLOR="good"
ENVIRONMENT="my-meza-env"
wiki_id="merged"
wiki_name="Merged Wiki"
wikis_to_merge="comma,separated,list,of,ids"
source /opt/slack-notify.sh
echo "Merge wiki ID = $wiki_id with name '$wiki_name'"
echo "Deleting wiki $wiki_id if it exists"
meza delete wiki-promptless "$ENVIRONMENT" "$wiki_id"
echo "Creating wiki $wiki_id"
meza create wiki-promptless "$ENVIRONMENT" "$wiki_id" "$wiki_name"
cd /opt/conf-meza/public
git reset --hard HEAD
meza deploy "$ENVIRONMENT" --tags mediawiki --skip-tags …
```
> Merge several wikis into one wiki

- src/roles/base/templates/config.php.j2
- src/roles/base/templates/config.sh.j2
- src/scripts/merge-pages/Main_Page.mediawiki
- src/scripts/unite-the-wikis.sh
- src/scripts/uniteTheWikis.php
Performs the same function as #992 but on the `27.x` branch.
> Backport to 27.x: merge wikis

- src/roles/base/tasks/main.yml
* Make sure to accept MS SQL EULA when upgrading packages, too.
None
> Accept MS SQL EULA

- Vagrantfile
Tested on `31.x` branch first. Ref #998.
> Vagrant mode fix - cherry pick from 31.x branch #998

- src/roles/haproxy/templates/haproxy.cfg.j2
* Adds HTTP Strict Transport Security (HSTS) header in HAProxy
* None
- None
> Add HSTS response header

- config/core/MezaCoreExtensions.yml
* Bump HeaderFooter to 3.0.0, for async headers and footers
None
None
> Bump HeaderFooter to v3.0.0

- config/core/MezaCoreExtensions.yml
* Forgot to remove legacy load on #1011 
None
None
> Remove legacy load from HeaderFooter

- config/core/MezaCoreExtensions.yml
* There have been many commits attempting to add Extension:TemplateData. For some reason I never merge them. Doing it this time.
* None
- None
> Actually add TemplateData this time

- src/roles/base/tasks/main.yml
- src/roles/base/templates/gitconfig.j2
- src/roles/mediawiki/tasks/main.yml
* Add `.gitconfig` for user `meza-ansible`
* Add fetch prune to gitconfig, to address #945
* Closes #945 
- None
> Do git fetch prune in meza-ansible's git-config

- config/core/MezaCoreExtensions.yml
* Bump bugfix releases for SMW and SRF
* None
- None
> Bump SMW to 2.5.8 and SRF to 2.5.6

- src/roles/saml/tasks/main.yml
* Bumps SimpleSamlPhp to latest bugfix release
* None
- None
> Bump SimpleSamlPhp to 1.15.4

- config/core/MezaCoreExtensions.yml
* Updates PageForms version
* None
- None
> Update pageforms to fix spreadsheet sorting

- config/core/defaults.yml
> Cleanup parsoid version comments

- config/core/MezaCoreExtensions.yml
- src/playbooks/rebuild-smw-and-index.yml
- src/roles/create-wiki-wrapper/tasks/main.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/mediawiki/templates/smw-rebuild-all.sh.j2
* Backported some fixes during testing of SMW 3.0
* Then made rebuildData improvements while troubleshooting SMW 3.0 issues.
* Pulling those improvements into master
* None
None
> SMW 3.0 fixes

- config/core/MezaCoreExtensions.yml
Gives spreadsheet sorting
* Adds PageForm spreadsheet sorting
* None
- None
> Bump PageForms

- config/core/defaults.yml
- src/roles/apache-php/templates/php.ini.j2
> Update php.ini.j2 add max input variables

- src/scripts/autodeployer/do-deploy.sh
Copying #1057 from 32.x onto master
> Reset +e prior to autodeployer deploys else second deploy fails

- config/core/MezaCoreExtensions.yml
Fixes critical bug for pending reviews
* WA 2.0.1
* None
None
> bump WatchAnalytics to 2.0.1

- Vagrantfile
Vagrantfile was trying to get info on app2 in cases when only db2 was configured.
* None
None
> Fix issue when vagrant VM db2 exists but app2 does not

- RELEASE-NOTES.md
Add release notes for 31.2.4
None
- Tag: 31.2.4
- Title: Meza 31.2.4
> RELEASE-NOTES for 31.2.4

- config/core/MezaCoreExtensions.yml
change references to this file to reflect it's current file name: MezaCoreExtensions.yml
change the word base-extensions to MezaCoreExtensions
> minor word change

- src/roles/meza-log/tasks/main.yml
* move source SQL files into place on remote DB servers (and slaves)
* ensure the SQL files are imported into the database
* Addresses #1110
> fix disk space logging

- config/core/MezaCoreExtensions.yml
* WatchAnalytics 3.0.0
* Approved Revs 1.0.0
* None
- None
> Bump WatchAnalytics/Approved Revs

- config/Debian.yml
- src/roles/base/tasks/main.yml
* Add direction to ufw configuration command
* Add missing Debian lua packages
> Configuration changes to get Debian working on WMCS again

- config/core/MezaCoreExtensions.yml
> Bump to WatchAnalytics 3.1.2

- config/Debian.yml
- config/RedHat.yml
- src/roles/mediawiki/tasks/main.yml
In addition to installing Python3, install PIP for Python3
N/A
- None
> Install PIP for Python3

- src/roles/firewalld/tasks/main.yml
- src/roles/haproxy/templates/errors/500.http.j2
change two minor spelling mistakes
none
none
> Minor spelling mistakes

- RELEASE-NOTES.md
> 31.4.0 release

- Vagrantfile
* In Vagrant, generate host/VM names that are unique
* In Vagrant, set `/opt/meza` to be owned by 10000:10000 instead of vagrant:vagrant. Want to be able to specify meza-ansible:wheel, but that is not possible due to the fact that mounting happens before Vagrant provisioning, and the user meza-ansible doesn't exist yet. So instead set numeric IDs and change the IDs after the fact.
Ref: hashicorp/vagrant#936
None
None
> Unique VM names, /opt/meza owned by UID/GID 10000 in Vagrant

- RELEASE-NOTES.md
> 31.5.0 release

- RELEASE-NOTES.md
> 31.6.0 release

- RELEASE-NOTES.md
Simplify push-backup settings and make cron configurable and with notification
N/A
> 31.7.0 release

- RELEASE-NOTES.md
> 31.8.0 release

- RELEASE-NOTES.md
See RELEASE-NOTES.md. Bug fix release.
None
None
> 31.8.1 release

- src/roles/verify-wiki/tasks/transfer-backup-to-db-master.yml
#1194 fixed several issues, but one variable didn't get fixed. Unfortunately it is not a tested case and didn't get noticed. Fixing.
None
None
> Fix bad variable usage

- src/roles/base/tasks/main.yml
* Fix bad owner/group on `/opt/data-meza`
None
None
> Fix bad owner/group on /opt/data-meza

- src/roles/update.php/tasks/main.yml
`update.php` doesn't currently write to a log. Fix that so issues can be diagnosed.
None.
None.
> Make update.php write to a log

- RELEASE-NOTES.md
> 31.8.2 release

- config/core/MezaCoreExtensions.yml
> Update MezaCoreExtensions.yml to include SESP

- config/core/MezaCoreExtensions.yml
* Bump SMW to 3.0.2
* None
- None
> Bump SMW to 3.0.2

- src/roles/database/tasks/replication.yml
- src/roles/remote-dir-check/tasks/main.yml
* Change from "something|skipped" to "something is skipped"
* Use set_fact boolean for whether something is skipped to simplify logic
* Update when syntax
* Closes #1240 
* #1090 addressed this and some other stuff, but master needs to be patched so it works now.
> Hotfix to master for ansible syntax updates in v 2.9

- RELEASE-NOTES.md
> 31.9.0 release

- config/core/defaults.yml
- src/roles/apache-php/tasks/ius.yml
- src/roles/apache-php/tasks/php.yml
- src/roles/mediawiki/tasks/main.yml
* Update IUS repo
* Extends #1254
- None
> Update IUS repo

- RELEASE-NOTES.md
Fix PEAR channel
* e048a7b Ensure PEAR channel up-to-date
* 2	James Montalvo
> 31.10.1 release

- .github/workflows/docker-build.yml
- src/scripts/meza.py
- tests/containers/base/Dockerfile
- tests/containers/full/Dockerfile
- tests/containers/max/Dockerfile
- tests/containers/pre-yum/Dockerfile
- tests/docker/init-container.sh
- tests/docker/init-controller.sh
- tests/docker/init-minion.sh
Previously Docker images used for testing were housed in separate repositories (see issue #911). This PR brings those Dockerfiles into this repo, and builds them in sequence on any new commit on `master`. So we'll get new, fresh images on each merged pull request. This should speed up testing.
* Closes #877
* Closes #911
- None
> Build Docker images used for test on each commit to master

- src/roles/apache-php/tasks/php.yml
- src/roles/apache-php/templates/php.ini.j2
* add LDAP module for PHP
* generically ensure PHP 5.x packages removed instead of 5.6 only
> add ldap module

- config/core/defaults.yml
* Bump MW to 1.31.7
None
- None
> Bump MediaWiki to 1.31.7

- src/roles/composer/tasks/main.yml
No actual change, just git cleanup
None
None
> Sync git network for 31.x and master

- config/core/MezaCoreExtensions.yml
* SMW 3.0.2 -> 3.2.2
* SRF 3.0.0 -> 3.2.0
* Addresses #1281
> SMW 3.2.2 and SRF 3.2.0

- RELEASE-NOTES.md
- src/scripts/do-release.sh
Fixes per #1173
* Closes #1173
> Fix: improve do-release.sh, iss #1173

- Vagrantfile
- src/roles/saml/tasks/main.yml
* Fixes broken installs for anyone using SAML
* chore(vagrant): bump vagrant box from bento/centos-7.4 to 7.9
> fix(saml): ensure SimpleSamlPhp actually installs

- src/roles/saml/templates/saml20-idp-remote.php.j2
* Allow specifying `saml_public.cert_data` or `saml_secret.cert_data` to allow full certificate rather than fingerprints
None
> feat: add SAML certData config
