enterprisemediawiki/meza

- README.md
- client_files/apache.sh
- client_files/httpd-conf-additions.conf
- client_files/mediawiki.sh
- client_files/mysql.sh
- client_files/php.ini-development
- client_files/php.ini-production
- client_files/php.sh
- client_files/yums.sh
- setup.sh
This pull request creates several shell scripts used to prepare the environment to build software from source (yum groupinstall development, plus some others), then install Apache 2.4, PHP 5.x.x, MySQL and MediaWiki.
> Add scripts for setting up dev environment, LAMP, and MediaWiki

- client_files/mediawiki-quick.sh
This pull request adds one file, mediawiki-quick.sh. The file is very similar to mediawiki.sh, but instead of checking out MediaWiki core from a git repository, the tarball for MW 1.25.1 is simply downloaded. This makes the install much faster. The Vector skin is also downloaded as tarball instead of git-cloned.
MediaWiki installation is then performed using the maintenance script install.php. Usage of this script requires two parameters to be passed: the mysql root password and the password for the wiki's Admin account (e.g. username = "Admin"). Usage is as follows:
```bash mediawiki-quick.sh <mysql-root-pass> <wiki-admin-pass>```
This script installs a wiki called TestWiki to a database named wiki_test.
> quick install without core.git download and use install.php

- client_files/php.sh
On install of MediaWiki a warning is issued stating that MediaWiki will fall back on its own internationalization functions rather than using the more efficient PECL versions. See issue #17.
> Add PECL internationalization extension to php.sh

- README.md
- client_files/ExtensionSettingsVE.php
- client_files/LocalSettingsVE.php
- client_files/VE.sh
- client_files/initd_parsoid.sh
- client_files/localsettings.js
This adds a new script VE.sh, several configuration files, and an init.d script to start the parsoid service on boot. I have tested this from the point of successful completion of extensions.sh. Note that VE.sh has several places where it uses wget to pull files that should already be available from the initial tarball. I'm not sure if we should change this now or wait until later.
TODO: Please change all instances of "installVE" to "master" in directories. This should be on lines 37, 40, 44, and 79.
Note that we will likely need to make some modifications to account for a private wiki per [this page](https://www.mediawiki.org/wiki/Extension:VisualEditor#Linking_with_Parsoid_in_private_wikis)
References:
* [init.d boot script](http://www.tldp.org/HOWTO/HighQuality-Apps-HOWTO/boot.html)
* …
> Install VE

- client_files/php.sh
PHP in PATH required to run mediawiki-quick.sh
> Run "exec bash" to make PHP command available immediately

- client_files/ExtensionSettings.php
Repositories from git.wikimedia.org do not appear as reliable as those from gerrit.wikimedia.org. As such, all repos of the form:
```https://git.wikimedia.org/git/mediawiki/extensions/ParserFunctions.git```
Are being changed to the following form in this pull request:
```https://gerrit.wikimedia.org/r/mediawiki/extensions/ParserFunctions.git```
> Change all git.wikimedia.org repos to gerrit

- client_files/apache.sh
Currently master (and all other active branches) are downloading Apache httpd 2.4.12, which does not exist at the location attempted to be downloaded from. We need to find a more robust way of downloading. As an emergency fix, bump httpd to 2.4.16
> Emergency fix: bump apache from 2.4.12 to 2.4.16

- client_files/VE.sh
- client_files/install.sh
- client_files/localsettings.js
The modified URI is the default VirtualBox IP address we're using.
This URI must be the endpoint URI that the user navigates to,
because when Parsoid serves up URIs for images (and probably other
resources) it uses this URI. So otherwise it goes looking for
images at http://127.0.0.1/<whatever>, which is on the user's
computer...doesn't work.
> Parsoid's setMwApi needs correct URI to use VE with images

- client_files/ElasticSearch.sh
- client_files/elastic-build-index.sh
- client_files/import-wiki.sh
Previously the "build index" steps were in the Elastic Search install script. Since importing a wiki may come after these steps, building of the index needs to be a separate task. Also, at times rebuilding the index may be required.
> Separate build-index script for Elastic Search

- client_files/ElasticSearch.sh
- client_files/install.sh
- client_files/yums.sh
RedHat has different repositories than CentOS, we've learned. In order to get access to the following packages the "rhel-6-server-optional-rpms" repository must be enabled.
* libc-client-devel.i686
* libc-client-devel
* libicu-devel
* t1lib-devel
* aspell-devel
* libvpx-devel
* libtidy-devel 
Additionally, architecture (32 vs 64 bit) is now autodetected rather than requested from the user. This was done in conjunction with autodetecting RedHat vs CentOS.
> Fix issue with certain yum repos not being available on RedHat

- client_files/install.sh
The cmdlog can sort of act as the simplified log since it's only logging the top-level commands, in theory.
> added cmdlog and generic log paths

- client_files/apache.sh
Simple change: just use different URLs for Apache sources so they don't break on new versions
Closes #80
Closes #139 (abandons changes)
> Use Apache archive URLs so links don't break on new versions

- client_files/ExtensionSettings.php
Settings were not being properly set for extensions due to local variables being called in "afterFn" functions. Change to use variables in the global context.
Closes #141
> Use vars in "afterFn" functions in global context

- client_files/ExtensionSettingsElasticSearch.php
In #49 all extensions in the main extension settings file were changed from git.wikimedia.org URLs to gerrit.wikimedia.org. These are faster and more reliable. I just had a test fail due to lack of Elastic Search extensions.
> Change Elastic Search extensions repo to gerrit

- client_files/import-wiki.sh
Was overwriting existing README and .htaccess files, then deleting README.md (doesn't exist) and the newly imported .htaccess files. Fixes these issues.
Also adds capability to use images.tar or plain directory, in addition existing images.tar.gz
> Improve wiki "images" directory import

- client_files/ExtensionSettings.php
- client_files/LocalSettingsAdditions
- client_files/install-imagick.sh
- client_files/install.sh
- client_files/yums.sh
Dependencies: ImageMagick, Ghostscript, xpdf-utils
ImageMagic is built from source since a more recent version
than what is in yum is required. The yum version of
Ghostscript is sufficient (for now), so it is used. There is
no yum version of xpdf-utils, so a pre-built binary is used.
> Install Extension:PdfHandler and dependencies from install.sh

- client_files/ExtensionSettings.php
- client_files/LocalSettingsAdditions
- client_files/install-imagick.sh
- client_files/install.sh
- client_files/yums.sh
Installs ImageMagick, which is the preferred method of handling image files with MediaWiki (rather than the PHP built-in GD). ImageMagick also provides the additional capabilities of:
* Rendering SVGs (though there may be better options, see #117)
* Rendering PDFs as images (using Ghostscript and Xpdf via the [PdfHandler](https://www.mediawiki.org/wiki/Extension:PdfHandler) MediaWiki extension).
Installation of ImageMagick is done from source, since the version available via yum is inadequate (see #18) and no suitable RPMs were available. Ghostscript is installed via yum. Pre-built executables are downloaded for Xpdf.
Closes #18
> Install Extension:PdfHandler, ImageMagick, Ghostscript and Xpdf

- client_files/VE.sh
In my last test, parsoid isn't loading:
When I list the contents of /usr/local/bin, I see the symlinks to node and npm are red. So it seems they are breaking. I might try this again using full paths (`/usr/local/bin/node-v0.12.7-linux-x64.tar.gz/bin/node node`).
Also note the `npm` command was not recognized during script execution:
```
******* Installing parsoid *******
VE.sh: line 60: npm: command not found
******* Testing parsoid *******
VE.sh: line 66: npm: command not found
```
> Pre built node

- manual/1.0-SettingUpVirtualBox.md
- setup.sh
Allows the user to choose an IP address during initial VirtualBox setup (e.g. in `setup.sh`, which I don't think has application except in Vbox VMs at the moment).
Defaults to 192.168.56.56, but can be modified when prompted.
> Allow choosing IP address during Vbox setup

- client_files/VE.sh
Fixes issue with Node not working on 32-bit operating systems. See #194.
**List of changes:**
* In `VE.sh` check whether the machine is 32 or 64 bit and download/install the appropriate version of Node.js
**How to test:**
Perform normal MediaWiki testing on 32-bit and 64-bit CentOS, with particular attention to making sure VisualEditor works.
**Issues:**
* Closes #194
> check for architecture, download appropriate node version

- client_files/import-wikis.sh
In `import-wikis.sh` the echoed title will be "import-wikis.sh" if that script is called directly, which would be the case if someone wanted to actually import wikis. However, `create-wiki.sh` also uses `import-wikis.sh`, so it'll print "create-wiki.sh" in that case (it'll print whatever the parent script is called). Furthermore, during initial install `create-wiki.sh` is called from within either `mediawiki.sh` or `extensions.sh`, which are called from within `install.sh`. Thus, it will display "install.sh" rather than the intended "import-wikis.sh". It's just easier to hard-code it, so that's what this PR does. It's a very minor change.
**Status:** Ready for merge.
**Testing:**
* Normal MediaWiki tests
**Issues:**
* Closes #192
> Explicitly print "import-wikis.sh" rather than script name

- client_files/config/LocalSettings.php
- client_files/config/httpd.conf
This pull request makes it so files cannot be accessed unless the user has access rights to the wiki. Prior to this file security is only provided by the obscurity of file URLs.
**Current status:**
Ready for merge.
**How to test this PR:**
See comment below from @jamesmontalvo3
**List of changes:**
* `$wgUploadPath` now routes all file requests (e.g. requests for images, PDFs, etc) through `img_auth.php`
* `httpd.conf` lots of random white space removed (done automatically by my editor)
* `httpd.conf` blocks direct access images directories
**Issues:**
* Closes #15
> Add security to uploads

- client_files/install.sh
This PR modifies the user prompts at the beginning of install.sh to expedite the user prompt portion.
**List of changes:**
* Generate a random 32-character (upper and lower case) password for MySQL root, but still allow the user to enter something different
* Detect the IP address and suggest that while still allowing the user to enter something different. This checks for eth1 (like our VMs). If there is no eth1, then it pulls the IP address from eth0 (like on our real server).
* For all other prompts, it displays the default value allowing the user to either change the value or just hit enter.
**How to test:**
1. `wget https://raw.githubusercontent.com/enterprisemediawiki/Meza1/detectip/client_files/install.sh`
1. `sudo bash install.sh`
1. Try using defaults vs your own values for the …
> Improve installer user prompts

- client_files/ElasticSearch.sh
Elasticsearch service was being registered in a method different from mysql and httpd services. It worked fine for CentOS 6, but for CentOS 7 it caused the service to not start upon reboot.
> Switch ElasticSearch service registration method

- client_files/ExtensionSettings.php
- client_files/VE.sh
- client_files/config/LocalSettings.php
This PR adds extensions Echo and Thanks. I included setting the parameter so that Thanks did not require verification (meaning one-click thanks instead of two-clicks).
It also removes a `cd` command that is unnecessary in the VE script.
1. `curl -LO https://raw.githubusercontent.com/enterprisemediawiki/Meza1/echo-thanks/client_files/install.sh`
1. `sudo bash install.sh`
1. Use branch `echo-thanks`
Closes #38 
Closes #48
> Add extensions Echo & Thanks

- setup.sh
This is to fix the branch specified in setup.sh - something that was supposed to be fixed before merging #186, but I missed that note once it was ready to merge.
> Forgot to update branch before merging #186

- CONTRIBUTING.md
Adding steps to explain how to test image access. At a later time this should be more easily configured for each wiki, so we can turn off anonymous viewing for one wiki but keep it on for another.
> Add specifics for testing image access

- CONTRIBUTING.md
Our testing requirements did not include creating/importing wikis.
> Add create and import wikis to requirements

- scripts/import-wikis.sh
This PR modifies the permissions of any wiki added using import-wikis.sh. Specifically it allows anyone to read and execute the wiki's directory and the config directory within that. This closes #232. There may be other, more tightly controlled ways of handling this, but it's what I could come up with based on some basic trial and error.
> update permissions to wiki and config path

- scripts/install.sh
- scripts/php.ini-development
- scripts/php.ini-production
- scripts/php.sh
This PR removes the prompt asking the user for which version of PHP they want to install. Now it is hard-coded to 5.6.14. This closes #24. This PR also adds lines to php.ini enabling and configuring OPcache. This closes #16.
Run install.sh on both CentOS 6 and 7 using the `opcache` branch:
* `curl -LO https://raw.githubusercontent.com/enterprisemediawiki/meza/opcache/scripts/install.sh`
* `sudo bash install.sh`
Verify OPcache was enabled by running `php -v` in the command line. You should see something like the following:
```
PHP 5.6.14 (cli) (built: Oct 18 2015 19:46:38) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```
You can also add a php.info file to …
> Hard-code PHP version, enable OPcache

- manual/2.1-CreateCloneVMs.md
This is a simple update to the manual for cloning VMs using CentOS 7.
To test, follow the steps to create a clone and verify you can SSH to the clone. Optionally run two VMs at once using two IP addresses.
> add CentOS 7 clone steps

- scripts/VE.sh
- scripts/install.sh
This PR checks out a specific version of parsoid. The version was chosen somewhat arbitrarily. We should test the currently-selected version, then try some newer versions to see if they work. We should try to identify which version breaks Parsoid for us and communicate that back to the WMF.
1. `curl -LO https://raw.githubusercontent.com/enterprisemediawiki/meza/parsoid-version/scripts/install.sh`
2. `sudo bash install.sh`
3. Use branch `parsoid-version`
4. Perform standard tests, with focus on VE.
* Closes #248 
* Address comments in #236 which were initially attributed to that issue (Flow) or to #161 (Upload Wizard)
> Checkout specific version of parsoid

- scripts/yums.sh
Adds yum package missing in CentOS 7, the absence of which was causing delays during install.
1. `curl -LO https://raw.githubusercontent.com/enterprisemediawiki/meza/deltarpm/scripts/install.sh`
2. `sudo bash install.sh`
3. Use `deltarpm` branch
4. Do standard testing.
* Closes #246
> Add deltarpm package to reduce install time

- CONTRIBUTING.md
Users should have to access via img_auth.php, so that MediaWiki
authentication is used to determine who can see the upload.
> No users should be able to directly access images

- scripts/config/LocalSettings.php
This is an update to LocalSettings.php to revise the list of namespaces on which VE and Flow are enabled. Additionally this addresses an issue where Flow was not enabled to use VE.
You can either just replace LocalSettings.php in a recent install (recommended) or do a full install (not recommended).
Optional full install steps:
* `curl -LO https://raw.githubusercontent.com/enterprisemediawiki/meza/flow-ve-settings/scripts/install.sh`
* `sudo bash install.sh`
* Use `flow-ve-settings` branch
* Verify VE works on `User`, `Help`, and `Project` pages
* Verify Flow works on a `Property` page (you can test the full list if you want, but this should be good)
* Use VE in Flow by toggling the button just above "Add topic"
* Closes #228
* Closes #269
> Edit NameSpaces using Flow/VE, allow Flow to use VE

- scripts/config/LocalSettings.php
- scripts/extensions.sh
In this pull request SummaryTimeline checks out tag `0.1.2`. Also, ExtensionLoader is upgraded to `0.2.3` in order to fix support for tags.
1. `curl -LO https://raw.githubusercontent.com/enterprisemediawiki/meza/extload-tags-fix/scripts/install.sh`
2. `sudo bash install.sh`
3. Use `extload-tags-fix`
4. Perform normal testing
5. Verify extensions load properly
6. Verify correct version of Summary Timeline
* Closes #148
> SummaryTimeline checkout tagged version

- scripts/import-wikis.sh
This PR closes #256 by temporarily setting wgDisableSearchUpdate to false before executing runJobs.php. This allows the job queue to clear without generating bogus search indices.
* Either run a full install of the `import-fix` branch or just swap this file out for the existing `import-wikis.sh` file
* Verify the OSO wiki on the FOD development server still has jobs in the queue (with job_attempts=0)
* Import the OSO wiki from the FOD development server
* Test ES
> Disable search update for runJobs during import

- scripts/apache.sh
- scripts/install.sh
This solves the no-firewall issue on CentOS 7 on Digital Ocean. Closes #287.
> Verify firewalld

- CONTRIBUTING.md
Just a change to the contributing guide to remind us to use debug when testing so we are notified of any notices, warnings or errors.
> Debug should always be on during testing

- scripts/VE.sh
- scripts/config/LocalSettings.php
- scripts/extensions.sh
- scripts/initd_parsoid.sh
- scripts/install.sh
- scripts/localsettings.js
- scripts/mediawiki.sh
This pull request will add MediaWiki 1.26 and extensions to the meza v0.9 branch.
* `curl -LO https://raw.githubusercontent.com/enterprisemediawiki/meza/mw1_26/scripts/install.sh`
* `sudo bash install.sh`
* Use `mw1_26` branch
* Perform normal tests.
* Parsoid changes
* Parsoid settings file `localsettings.js` moved from `/etc/parsoid/api` directory to `/etc/parsoid`. Could not find when in Parsoid development that requirement changed.
* Parsoid `server.js` moved to `/etc/parsoid/bin`
* Checking out parsoid commit `8976ab9`, which was the latest commit as of my testing. Ideally there would be a branch or a tag we could checkout, but that does not appear to be the case
* Add "domain" param to localsettings.js parsoidConfig
* Checking out REL1_26 branch of all extensions
* …
> Install MediaWiki 1.26

- scripts/config/httpd.conf
In httpd.conf, this PR allows POST, PUT and DELETE requests to the Elasticsearch API. Without the ability to do POST it's impossible to do complex queries from ES management tools like Kopf. The API is still under authentication, so a username/password is required. If at some point in the future we need to re-restrict this that's fine, but during pre-v1.0 development it'll be nice to have easy access.
* Assists with #70 
* Assists with #182 
* Assists with #296 
* Assists with #299
> Relax elasticsearch API access to allow POST/PUT/DELETE

- scripts/mediawiki.sh
Bumping to MW 1.25.5 from 1.25.1.
* `curl -LO https://raw.githubusercontent.com/enterprisemediawiki/meza/mw1.25.5/scripts/install.sh`
* `sudo bash install.sh`
* Use `mw1.25.5` branch
* Perform normal tests. 
Closes #313
> Bump to MW 1.25.5 from MW 1.25.1

- scripts/config/LocalSettings.php
Fixes issue of images not displaying in VE when the images existed already on the page. Newly-added images via VE always displayed well. See #329.
* Make`$wgServer` get re-written to `https://<domain>` when parsoid accesses wiki via `http://<domain>:9000`.
* Closes #329
> Fix images in VE

- scripts/config/LocalSettings.php
Add Extension:CollapsibleVector to bring back collapsible items in the sidebar. This feature was removed in a recent version of the Vector skin, and this extension adds it back in.
* Add Extension:CollapsibleVector
* Closes #310
> Add Extension:CollapsibleVector

- scripts/config.sh
`saml.sh` relies upon the `$m_apache` variable in `config.sh`. This variable was still set to the compiled-apache location. This PR changes it to the yum-installed location.
> fix m_apache config var to point to yum install

- README.md
- config/meza/LocalSettings.php
- config/template/more-extensions.php
- manual/installing-additional-extensions.md
Provide method for handling custom extensions.
* Removes SummaryTimeline and IMSQuery as default meza extensions
* Adds `/opt/meza/config/template/more-extensions.sh` as a template for how to add non-meza extensions, which includes SummaryTimeline, IMSQuery, and three other FOD-required extensions
* Documentation on the most-mezaiatic method for adding extensions
* Closes #150 
* Closes #151
> Provide method for handling custom extensions

- scripts/elastic-build-index.sh
- scripts/elastic-rebuild-index.sh
Provides method to rebuild an Elasticsearch index. Really this is just using all of the existing CirrusSearch scripts, but the `elastic-rebuild-index.sh` script handles all the finer points. This is as-opposed to the `elastic-build-index.sh` script that already exists for wiki create/import.
* Added `--startOver` option to `updateSearchIndexConfig.php` so it'll "blow away" the current index(es).
* Added `/opt/meza/scripts/elastic-rebuild-index.sh` which is a wrapper for `elastic-build-index.sh` and rebuilds an index from scratch
* Closes #70
> Provide method to rebuild Elasticsearch index

- config/meza/LocalSettings.php
- config/template/BlenderSettings.php
- scripts/apache.sh
- scripts/import-remote-wikis.sh
- scripts/import-wikis.sh
- scripts/saml.sh
- scripts/unifyUserTables.php
Several miscellaneous fixes for release v0.9
* Debug is now always on for MW maintenance scripts
* Memcached is disabled for sessions because it conflicts with SimpleSamlPhp
* Fixed domain name for WikiBlender
* Fixed `sed` on `httpd.conf`, which was breaking the symlink (#353)
* `import-remote-wikis.sh` now uses `rsync` to get files and is more verbose. It also is more verbose when doing `mysqldump`.
* `saml.sh` makes sure to generate `overrides.php` if it doesn't exist, so the file starts with `<?php`
* `unifyUserTables.php` now does self-tests to confirm changes are applied properly
* Closes #205
* Closes #353
* Closes #350
> Miscellaneous fixes for release v0.9

- config/core/LocalSettings.php
This PR mods LocalSettings.php in order to modify UploadWizard, limiting the licensing options to a single default generic option.
* Remove comment to issue that is now closed and no longer seems applicable
* Add config to LocalSettings.php to make use of generic default licensing option
* Closes #251
#156 seems to be closed/abandoned, so I'm removing reference from code
Add licensing config based on https://gerrit.wikimedia.org/r/#/c/283110/5/README
> UploadWizard LocalSettings default generic license

- scripts/yums.sh
EPEL for CentOS 7 no longer is at version 7.5. It is now 7.6. The URL for 7.5 no longer works and must be fixed immediately. Without this libmcrypt cannot be installed (via `yum`) which makes it impossible to build PHP.
* Fixes URL for CentOS 7 EPEL repository
* Closes #374
> EPEL now 7.6 vs 7.5 for CentOS 7, hotfix #374

- config/core/LocalSettings.php
Include Extension:Math, which was already part of FOD2 wikis. This somewhat addresses #122, but really we should enable some side of server-side rendering.
> add Extension:Math, which already exists on FOD2

- .gitignore
- config/core/elasticsearch.yml
- config/core/my.cnf
- data/README.md
- data/elasticsearch/README.md
- data/mysql/README.md
- scripts/ElasticSearch.sh
- scripts/imagemagick.sh
- scripts/mysql.sh
Move elasticsearch and mysql data to `/opt/meza/data` rather than locations in `/var`. This was done for some security compliance reasons.
* Create `/opt/meza/data` directory (gitignore all) and required placeholder READMEs to make space for MySQL and Elasticsearch data.
* Adjust path config for Elasticsearch in `elasticsearch.yml` (also auto-whitespace fixes)
* Modify `ElasticSearch.sh` to create necessary sub-directories of `/opt/meza/data/elasticsearch` and properly `chown` them.
* Create `/opt/meza/config/core/my.cnf`. Previously was using the default `/etc/my.cnf` file provided by `yum` install. This file is no symlinked from `/etc/my.cnf`. This file specifies the `/opt/meza/data/mysql` directory for data, and maintains the socket location in `/var/lib/mysql/mysql.sock` due to …
> Move elasticsearch and mysql data to /opt/meza/data

- config/template/imagick-secure-policy.xml
- scripts/imagemagick.sh
Adds policies to Imagemagick to prevent remote code execution which was discovered on 03-May-2016. See:
* [imagemagick.org description of vulnerability](https://www.imagemagick.org/discourse-server/viewtopic.php?t=29588)
* https://imagetragick.com/
* [imagemagick.org policy configuration](https://www.imagemagick.org/discourse-server/viewtopic.php?f=4&t=26801)
* [Wikitech mailing list](http://www.gossamer-threads.com/lists/wiki/wikitech/706628)
> add policies to imagemagick to prevent remote code execution

- scripts/VE.sh
Remove the parsoid tests (`npm test`) in `VE.sh` since we don't check for passing anyway. It just takes time during install. #387 has been created to track turning this feature back on optionally if someone wants to run tests.
> Remove parsoid tests

- scripts/mediawiki.sh
Before composer-merge-plugin v1.2.0 [0], MediaWiki incorrectly required v1.0.0 of the Composer internal composer-plugin-api component. Composer recently bumped this internal version to v1.1.0 [1]. A patch to MediaWiki is in work, but until it is in place this change to meza is required to prevent failed builds.
[0]: https://github.com/wikimedia/composer-merge-plugin/releases/tag/v1.2.0
[1]: https://github.com/composer/composer/commit/aeafe2fe59992efd1bc3f890b760f1a9c4874e1c
According to WMF's Bryan Davis, the quick fix is to edit $IP/composer.json and change the `"wikimedia/composer-merge-plugin": "1.0.0",` line to read `"wikimedia/composer-merge-plugin": "1.3.1",``.
* Manually modify MediaWiki's `composer.json` so proper version of composer-merge-plugin is pulled
> Fix composer api version conflict

- scripts/yums.sh
Hotfix to use new version of EPEL. Build fails without this.
> Hotfix bump epel version to 7.7

- scripts/extensions.sh
Hotfix. Tie SMW to a stable release
> Tie SMW to the 2.4 branch. Getting install failures due to 2.5-dev

- scripts/yums.sh
The [EPEL](https://fedoraproject.org/wiki/EPEL) version was hard coded prior to this PR. As such, when a new version was released the download URL would no longer be valid since only the latest version is available.
* Determine EPEL version prior to attempting to download
* Related to issue #374 and PRs #375 and #401
> Check EPEL version before arbitrarily trying to download it

- scripts/install.sh
This moves the check for (and installation of) firewalld after all the user prompts. Before this PR, if firewalld is not installed, the user may think they're done and can walk away due to the firewalld installation output. After this PR, all the user prompts will be immediately after issuing the install command.
* Closes #399
> Check for and install firewalld after all prompts

- config/template/composer.local.json
- scripts/extensions.sh
Without migrating to the new method of putting Composer-based extensions into `composer.local.json` instead of `composer.json`, was getting the following error:
> Notice: Undefined index: hash in /opt/meza/htdocs/mediawiki/includes/libs/composer/ComposerLock.php on line 19
I don't understand why this suddenly broke. The same versions of MediaWiki are being pulled in both the MW 1.25 branches tested (`master`, `rpm`) and the MW 1.27 branches (`mw1.27`, `modules`) as were being pulled the last time we were getting successful installs. It must therefore be an issue with either the extensions using Composer (those now in `composer.local.json`) or the libraries that MW Core uses (those defined in `composer.json`).
Ref: https://www.mediawiki.org/wiki/Composer/For_extensions
> Use composer.local.json to avoid composer errors

- config/core/LocalSettings.php
- config/core/initd_parsoid.sh
- config/core/localsettings.js
- scripts/VE.sh
- scripts/extensions.sh
- scripts/install.sh
- scripts/mediawiki.sh
- scripts/php.sh
Much development has been going on to make meza support a multi-server environment. This has created a chain of development branches all building off of each other. Rather than maintain this confusing chain, I'm merging them all into a `dev` branch.
The `mw1.27` branch started using MediaWiki 1.27.
Ref #462 for more cleanup
> Cleanup development: `mw1.27` branch merged into `dev` branch

- .gitignore
- README.md
- ansible/env/example/hosts
- config/core/config.sh
- scripts/meza.sh
Allows running command `meza install monolith`. This will prompt for the IP address or domain of the server you're running the command on, and then install everything upon it. Alternatively, do `meza install monolith IPADDR` (with IPADDR = the desired IP or domain) to avoid prompts. This will be used by TravisCI.
> Make `meza install monolith` work again

- ansible/env/example/hosts
- ansible/roles/firewalld/tasks/main.yml
- ansible/roles/haproxy/templates/haproxy.cfg.j2
- scripts/meza.sh
Allow ansible localhost connections such that a server doesn't have to SSH into itself. Also this makes it so on `meza install monolith` you don't need to type the IP address of the server. It now listens to all IP addresses.
> Allow ansible local connections

- .travis.yml
- README.md
- ansible/roles/apache-php/tasks/php.yml
- ansible/roles/base/tasks/main.yml
- ansible/roles/elasticsearch/tasks/main.yml
- ansible/roles/haproxy/tasks/main.yml
- scripts/getmeza.sh
- scripts/meza.sh
Start running tests on TravisCI. 
On a VM with a clean CentOS 7 min install:
* Show "build status" badge on main README. Note, this looks at the build status of the `dev` branch for now, since this won't likely be merged into `master` soon. That will need to be fixed when it is merged into `master`. Created issue TBD to track.
* Added package `mariadb-libs` to app-server installations. This package comes with CentOS 7 min install, so it is not required for most installations, but it does not come with the Docker image being used in TravisCI. This package is a dependency for some portion of PHP, which `yum` will detect and attempt to fulfill if not explicitly called out, so in theory it shouldn't be required. However, due to the fact that we're using the IUS repository for PHP 5.6 (e.g. …
> Start using Travis CI

- ansible/getdocker.yml
- manual/meza-cmd/docker.txt
- scripts/build-docker-container.sh
- scripts/meza.sh
Adds commands:
* `meza install docker`: install Docker on CentOS 7
* `meza docker run [optionally specify repo for base image]`: Downloads image from Docker Hub (if not already present), boots it, runs `build-docker-container.sh` to make a monolith.
* `meza docker exec <container-id> [whatever command you want to run]`: run arbitrary commands against the container
> Commands for setting up docker (on CentOS) and executing commands on container

- .gitignore
- ansible/backup.yml
- ansible/paths.yml
- ansible/roles/backup-db-wikis/tasks/main.yml
- ansible/roles/backup-uploads/tasks/main.yml
- ansible/roles/dump-db-wikis/tasks/main.yml
- ansible/roles/mediawiki/templates/LocalSettings.php.j2
- ansible/roles/update.php/tasks/main.yml
- ansible/roles/verify-wiki/tasks/main.yml
- ansible/template-env/blank/hosts
- scripts/meza.sh
- test/travis/run-tests.sh
Now can do `sudo meza backup <environment>`. And then when another environment does `sudo meza deploy <another environment>` it can pull from that backup.
* Moves images/uploads from `$m_htdocs/wikis/$wikiId/images` to `$m_meza/data/uploads/$wikiId`
* Backups sent to and pulled from `/opt/meza/backups/{{ wiki_id }}`
* Added tests to `run-tests.sh` to have backup database/uploads, then uses API to find an image from that backup, and verify it is present (was imported correctly).
> Add create-backup functionality, integrate with `meza deploy`

- README.md
- scripts/getmeza.sh
Fixes some references to `dev` branch in README, plus tells the `getmeza.sh` to get the `master` branch instead of  `dev`.
> Fix references to 'dev' branch, point to master

- .codeclimate.yml
- README.md
Changes only to README (add badge) and `.codeclimate.yml` to tell Code Climate to check shell scripts
> Make CodeClimate's ShellCheck work; add CodeClimate GPA badge to README

- manual/meza-cmd/backup.txt
- manual/meza-cmd/base.txt
- manual/meza-cmd/create.txt
- manual/meza-cmd/deploy.txt
- manual/meza-cmd/docker.txt
- manual/meza-cmd/install.txt
- manual/meza-cmd/setup.txt
- scripts/meza.sh
Improve help files for meza command, so `meza --help` is more useful. Also cleaned some things up in `meza.sh` (the meza command file) to remove unused items and flagged some items as likely to be removed or reworked.
> Improve meza command help files

- ansible/roles/mediawiki/templates/LocalSettings.php.j2
- ansible/template-env/blank/group_vars/all.yml
- scripts/meza.sh
`LocalSettings.php` had `$wgSecretKey` set to a single value, which was very insecure. Now it will be randomly generated when a new environment is created. Value should be set in `group_vars/all.yml`.
> Don't hard-code secret key, random generate on setting up new env

- ansible/roles/base/tasks/main.yml
Build failed on a multi-server setup where Parsoid was on its own server. Meza needed to use git to checkout Parsoid and failed. The server that had Parsoid on it had only had the following commands run on it directly prior to the control server starting to configure it:
```
sudo ifup enp0s3
curl -L minion.getmeza.org > doit
sudo bash doit
curl -L vbox.getmeza.org > doit2
sudo bash doit2
```
None of those steps install Git. They were followed by the control server pushing its SSH keys to this minion and then `meza setup env myenv` and `meza deploy myenv` which began installing meza across all the wikis.
When installing a monolith you setup the meza command with `curl -L getmeza.org > doit` and `sudo bash doit` and that installs git. Since that step is not required when setting up a minion …
> Ensure all servers have git installed

- src/playbooks/backup.yml
- src/playbooks/create-wiki-promptless.yml
- src/playbooks/create-wiki.yml
- src/playbooks/setup-env.yml
- src/playbooks/site.yml
- src/roles/init-controller-config/tasks/main.yml
- src/roles/init-controller-config/templates/vars.yml
- src/roles/set-vars/tasks/main.yml
- tests/travis/run-tests.sh
Previously local-public config had a file `deploy-config.yml` which was an attempt to override `/opt/meza/config/core/paths.yml` and other config vars. However, it did not work properly. This PR sets it up to work, such that any config variable can be overriden. This allows basic configuration changes like setting the title on the landing page, or changing the path to the backups directory.
* `deploy-config.yml --> vars.yml`
* Loading of `vars.yml` and `paths.yml` now performed by role `set-vars` instead of a `vars_files` call
* Closes #502
> Improve optional variables handling

- manual/1.0-SettingUpVirtualBox.md
- manual/SetupRedHat.md
- src/roles/apache-php/tasks/ius.yml
- src/roles/base/tasks/main.yml
- src/scripts/dev-networking.sh
- src/scripts/getmeza.sh
A description of the pull request
* Add [manual/SetupRedHat.md](manual/SetupRedHat.md) for getting a Red Hat dev license and setting up a VM
* Fix IUS repo download for Red Hat. Conditional had bad value when checking for Red Hat
* Make role:base properly ensure EPEL exists for Red Hat. For CentOS you simply need to do `yum install epel-release`. For Red Hat you need to get EPEL from a URL
* Also make `dev-networking.sh` properly install EPEL
* Remove CentOS 6 lines from `dev-networking.sh` which conflicted with RHEL 7 and were pointless anyway
> Support RedHat 7

- src/roles/database/defaults/main.yml
This change must have been overwritten at some point, because we have been keeping data in `/opt/meza/data` for a very long time. This was a simple change because the Ansible role for MySQL/MariaDB handles the change. This PR sets the default to `/opt/meza/data/mariadb`, but it is possible to override this in a meza instance's settings.
> Move mariadb data directory

- src/roles/mediawiki/files/MezaCoreExtensions.yml
Added Semantic Drilldown extension to list of core extensions.
Tested deploy on fresh install of CentOS 7 and worked w/o issue.
> Added Semantic Drilldown to Core Extensions

- .gitignore
- Vagrantfile
Use Vagrant to initiate meza in VirtualBox:
1. Download and install [Git](https://git-scm.com/), [VirtualBox](https://www.virtualbox.org/), and [Vagrant](https://www.vagrantup.com/)
2. `git clone https://github.com/enterprisemediawiki/meza`
3. `cd meza`
4. `vagrant up` (Takes about 20-30 minutes)
5. Use meza at https://192.168.56.56
6. SSH into the machine by doing `vagrant ssh`
Documentation will come in a later PR after spending time using Vagrant with meza.
> Enable install with Vagrant

- Vagrantfile
`vagrant up` now rsyncs the whole Vagrantfile directory into `/opt/meza` including `.git` directories and symlinks. This allows having MW and extensions in `htdocs/mediawiki` pre-cloned on the host, which will be transferred to the guest. This shaves several minutes off install.
> Allow MW and extensions on host to be rsynced to guest

- src/roles/mediawiki/templates/LocalSettings.php.j2
Check for presence of HTTP_X_FORWARDED_FOR to determine if request is from
a real user or if it is a request from a service. If it's a service, then
set permissions to be able to view/edit all. Real users will have
HTTP_X_FORWARDED_FOR, service request (that don't go through the load
balancer) do not.
> Fix permissions for services accessing MediaWiki

- src/roles/mediawiki/templates/LocalSettings.php.j2
Extension:TalkRight permissions were not being set. Allow users who can view but not edit to be able to talk. This is replacing #452.
> Fix talkright permissions

- src/roles/mediawiki/files/MezaCoreExtensions.yml
Missing extension commonly bundled with MW. Closes #438.
> Add extension ImageMap

- src/roles/apache-php/tasks/main.yml
- src/roles/base/tasks/main.yml
In order for user `meza-ansible` to perform some actions it must be part of the groups "wheel" and "apache". This allows the user to perform actions without `sudo`. This particularly came into play when working on backups and imports where the meza-ansible user may be invoked outside of the normal Ansible methods.
Closes #510
> Add meza-ansible to groups wheel and apache

- src/scripts/getmeza.sh
Minimal install of CentOS and RHEL doesn't include SELinux. Currently [libselinux-python is explicitly installed before SELinux](https://github.com/enterprisemediawiki/meza/blob/a49d61a453acdeb3a917befd4931ec25eaa806de/src/roles/base/tasks/main.yml#L42) in role "base". This satisfies Ansible's requirements for SELinux. However, if SELinux is pre-installed on the system without libselinux-python then the following error occurs:
> Aborting, target uses selinux but python bindings (libselinux-python) aren't installed.
This PR fixes this by adding `yum install libselinux-python` to `getmeza.sh`.
Closes #509
> Add libselinux-python to getmeza.sh for initial conditions

- Vagrantfile
Adds a deploy option to `vagrant up` command via environment variable. Now you have to options:
1. `vagrant up` will deploy a basic monolithic installation
2. `deploy=none vagrant up` will just install the `meza` command and dependencies. This allows the user to then `vagrant ssh` to login and perform `sudo meza deploy monolith` or whatever other custom commands required. Note that the IP address `192.168.56.56` must be chosen.
> Add deploy option to `vagrant up`

- .gitignore
- config/core/app-ansible/README.md
- config/core/paths.yml
- src/roles/base/tasks/main.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/mediawiki/templates/LocalSettings.php.j2
- src/roles/sync-configs/tasks/main.yml
- tests/travis/run-tests.sh
Use rsync (with option to exclude `.git` directories) to transfer config from controller to app servers. Without this, the transfer of `.git` directory contents was taking 3.5 minutes if the `local-public` directory was a git repository. Changing to rsync (Ansible `synchronize`) with the `delete: yes` option also ensures that any files that are removed from the config do not continue to reside on app servers. However, this change made it so `Extensions.php`, which is an Ansible-generated file not originating from `local-public`, was being overwritten by the rsync-delete. Instead it is now placed in `config/core/app-ansible`.
Also changed `run-test.sh` for the 2-Docker-container test to change `git describe --tags` to `git rev-parse HEAD`. `describe --tags` fails if no tags present, and …
> Fix really long delay in syncing configs due to also syncing .git directory

- tests/travis/git-setup.sh
Missing `$` on variable when checking out branch. This created a chicken-vs-egg situation for following pull requests, not allowing them to checkout the appropriate branch.
> Fix branch checkout for travis PRs

- tests/travis/git-setup.sh
Need to do `git merge origin/branchname`, not just `git merge branchname`, when performing required merge for Travis CI pull request tests.
> Fix travis merging of pull request tests

- tests/travis/git-setup.sh
During testing of pull requests, it is necessary to do a `git merge` to generate the PR commit (merged commit). This `git merge` requires `git config` to be setup.
> Need git config for PR merge test

- .travis.yml
- src/playbooks/site.yml
- src/roles/apache-php/tasks/main.yml
- src/roles/base/tasks/main.yml
- src/roles/grant-keys/tasks/main.yml
- src/roles/revoke-keys/tasks/main.yml
- src/roles/verify-wiki/tasks/init-wiki.yml
- src/roles/verify-wiki/tasks/main.yml
- src/scripts/meza.py
- tests/deploys/setup-alt-source-backup.yml
- tests/docker/import-from-alt-remote.setup.sh
- tests/docker/run-tests.sh
Modified `src/roles/verify-wiki/tasks/main.yml` and `src/scripts/meza.py` to support `--overwrite` (or `-o`) option when running `meza deploy`, which makes the deploy overwrite existing data (database and uploads) for all wikis, if the source data exists. Use it like:
```
sudo meza deploy staging --overwrite
```
Modified `src/roles/verify-wiki/tasks/main.yml` to support two additional groups in hosts inventory: `db-src` and `backup-src`. These two groups are intended as sources of backup data only. They will not be used for the installation to pull backups from.
Use the following to specify a server as a db-src in your `local-secret/<your env>/hosts` file. This will tell `meza deploy` to make a `mysqldump` of the appropriate database on that server.
```
[db-src]
192.168.56.100
```
Since …
> Allow pulling database/uploads from alternate sources

- src/roles/apache-php/tasks/main.yml
- src/roles/haproxy/tasks/main.yml
Prior to this PR, SSL cert/key was auto-generated if not present in HAProxy directory. There was no way to have keys located in a local config and pushed to load balancers. This fixes that.
* Remove unused SSL config from Apache
> Use SSL cert from config if exists

- src/roles/mediawiki/templates/LocalSettings.php.j2
`LocalSettings.php` had localhost hard-coded as the memcached server. This needs to create an array of servers from inventory hosts.
> In LocalSettings.php use memcached servers from inventory

- src/roles/mediawiki/tasks/main.yml
Add tag `verify-wiki` and `update.php` to make it possible to `--skip-tags` for checks on MW database/uploads. Closes #555.
> Add tags for update.php and verify-wiki

- src/roles/mediawiki/templates/LocalSettings.php.j2
The concept of "primewiki" was unintentionally removed. This adds it back in a more Ansible-y way. In short, to make a particular wiki the primewiki, add to config (e.g. `/opt/meza/config/local-public/vars.yml`) the following:
```yaml
primary_wiki_db_name: wiki_fod
```
Where `fod` is the Wiki ID for the wiki you want to use for the `user`, `user_properties`, and `interwiki` tables.
> Reenable primewiki functionality

- config/core/MezaCoreExtensions.yml
- src/roles/verify-wiki/tasks/init-wiki.yml
- tests/docker/init-controller.sh
This PR changes SemanticMeetingMinutes (SMM) to *not* use Composer for installation. Composer generally complicates install, and since SMM has minimal dependencies it is easier to keep them in `MezaCoreExtensions.yml` instead.
Other changes:
* Add [Extension:PageImporter](https://github.com/enterprisemediawiki/PageImporter), a new dependency for SMM which handles importing required pages (forms, templates, properties, etc)
* Explicitly require [HeaderFooter](https://www.mediawiki.org/wiki/Extension:Header_Footer) and [NumerAlpha](https://www.mediawiki.org/wiki/Extension:NumerAlpha) in `MezaCoreExtensions.yml` rather than having them as implicit dependencies via Composer. This also upgrades the NumerAlpha version.
* Use PageImporter's `importPages.php` to import pages rather than MW's …
> Upgrade SemanticMeetingMinutes; don't use Composer; add PageImporter

- config/core/paths.yml
- src/roles/backup-db-wikis/tasks/main.yml
- src/roles/base/tasks/main.yml
- src/roles/database/tasks/replication.yml
- src/roles/dump-db-wikis/tasks/main.yml
- src/roles/update.php/tasks/main.yml
- src/roles/verify-wiki/tasks/main.yml
The intent of meza is to be easy to configure. By stating that the bulk of your free space needs to be in `/opt` it makes it easier to decide on partition sizes. However, backup scripts and other scripts moving files (particularly uploads (aka images)) and database dumps were clogging up the `/tmp` directory. Instead use `/opt/meza/data/tmp`.
> Use /opt/meza/data/tmp instead of /tmp, particularly for large files

- src/roles/mediawiki/defaults/main.yml
- src/roles/mediawiki/templates/LocalSettings.php.j2
Provide options to allow configuration to specify debug mode. Add to `/opt/meza/config/local-public/vars.yml`:
```yaml
m_force_debug: true
m_command_line_debug: true
```
> provide options to enable debug mode

- config/core/MezaCoreExtensions.yml
The imagesloaded script was broken out of MasonryMainPage since it was being used also by MediaWiki:Common.js on some wikis. It therefore needs to be loaded even when MasonryMainPage is not.
> Use ImagesLoaded extension, now separate from MasonryMainPage

- src/roles/mediawiki/templates/LocalSettings.php.j2
Tell Universal Language Selector not to try to guess language based upon IP address. This (a) isn't likely needed in enterprise use cases and (b) fails anyway due to outdated URLs or firewall rules.
Without this you get these errors in JS console:
> Turn off geoip guessing

- config/core/MezaCoreExtensions.yml
Replaced Semantic Forms with Page Forms 4.1. Tested on VM running latest meza master branch.
> Added Page Forms 4.1

- config/core/MezaCoreExtensions.yml
Fix versions for extensions, plus fix var names for HeaderTabs
> HeaderTabs, Pipe escape, and CopyWatchers versions

- src/playbooks/rebuild-smw-and-index.yml
- src/roles/create-wiki-wrapper/tasks/main.yml
- src/roles/mediawiki/tasks/main.yml
On previous PR #581 SMW's `rebuildData.php` swapped order to be after Elasticsearch index rebuilding. However, the names of the tasks and the functions of the tasks were not aligned, so the order was not actually swapped as desired. This PR cleans that up.
SMW data rebuild should be second because (a) it takes a really long time, (b) it is not always required per discussion on SMW mailing list, and (c) even if it is required it is less detrimental to a new server to not have search index than to not have SMW data be perfect.
> Fix SMW/Elastic rebuild order; names/functions misaligned

- config/core/MezaCoreExtensions.yml
Stop using `extreg` branch which was missing fix for `wfchecklimits` function
> Use Wiretap master, don't legacy-load

- src/roles/database/tasks/replication.yml
- src/roles/verify-wiki/tasks/main.yml
Ansible, as provided by `yum` via EPEL, jumped from v2.2.1 to v2.3 in the last day. On one day the build passed, and the next day it failed:
* [Passing build from 26-APR-2017](https://travis-ci.org/enterprisemediawiki/meza/builds/226090878)
* [Log line showing Ansible 2.2.1](https://travis-ci.org/enterprisemediawiki/meza/jobs/226090879#L324)
* [Failing build from 27-APR-2017](https://travis-ci.org/enterprisemediawiki/meza/builds/226481748)
* [Log line showing Ansible 2.3](https://travis-ci.org/enterprisemediawiki/meza/jobs/226481749#L328)
> Fix conditional checks failures that arose when Ansible 2.2.1-->2.3

- config/core/MezaCoreExtensions.yml
Extension:Math after MediaWiki 1.25 does not allow client-side rendering
of Math via the MathJax javascript library. Without this it is required to
install a server side renderer such as Mathoid, texvc, or LaTeXML. All of
these are complicated. At some point down the road perhaps we'll add one
(or more) of these, but for now it is much simpler to maintain previous
functionality with this other extension.
Note that the original SimpleMathJax had two issues:
1. The MathJax library was loaded from a CDN, which is a
security/privacy concern
2. MathJax JS and CSS was loaded with every page load, regardless of
whether or not <math> or <chem> tags were used
As such, the GitHub jmnote/SimpleMathJax repo was forked to
jamesmontalvo3/SimpleMathJax. The changes made in this fork have been …
> Use Extension:SimpleMathJax instead of Extension:Math

- config/core/MezaCoreExtensions.yml
- src/roles/memcached/tasks/main.yml
This PR closes two issues:
* Closes #602: Swap out Maps for Semantic Maps. Semantic Maps was discontinued at v3.8 (we had ~3.2 specified, which via Composer rules gave us the latest v3.8). Semantic Maps was then merged into Extension:Maps, which as of this writing has stable version 4.1. This PR switches to using that.
* Closes #416: Install netcat. This is already present on meza monoliths, but it is possible that it may not be installed on standalone memcached servers. As such, it was added to role:memcached. Additionally, several cleanup/standardization changes were made to this file.
> Maps not Semantic Maps; Install netcat

- src/roles/mediawiki/templates/Extensions.php.j2
The contents of `Extensions.php` (a PHP script generated by Ansible with data from `MezaCoreExtensions.yml` and `MezaLocalExtensions.yml`) had duplicate config entries for meza-core Composer-installed extensions due to a type (copy-paste error). See #598. This fixes that.
* Closes #598
> Fix Extensions.php to use meza_local_extensions where appropriate

- tests/docker/init-controller.sh
Cleaning up Docker image used after chicken-and-egg problem created by #619
> Reorg (#619) complete and meza-docker-full rebuilt: use latest image

- src/roles/mediawiki/templates/LocalSettings.php.j2
- src/roles/parsoid/tasks/main.yml
- tests/docker/import-from-remote.setup.sh
Parsoid does not allow <img> tags and doesn't show no respect for `$wgAllowImageTag`. This PR adds a config variable `allow_image_tags` which:
1. Sets `$wgAllowImageTag` to true or false, accordingly
2. If `allow_image_tags` is true, patches Parsoid to allow image tags
This is a sort of temporary fix until MediaWiki/Parsoid are fixed. This may take some time, though, since it first requires a MediaWiki core patch, then a Parsoid patch, then we have to wait to catch up with the versions we use (or get them to back-port to MW 1.27 (possibly doable) and to our Parsoid version (not likely)). This will continue to be followed in #149.
> Optionally allow <img> in wikitext, and make work in VE

- src/roles/cron/defaults/main.yml
- src/roles/cron/tasks/main.yml
- src/roles/cron/templates/meza-ansible.crontab.j2
- src/roles/cron/templates/runAllJobs.php.j2
Closes #496
* Allow configure cron time for server performance, disk space scripts
* configure cron time for frequent and full runJobs.php
* configure frequent runJobs.php with number of jobs, max wiki time, max total time, max server load
* parsoid restart nightly or whenever desired
* allow custom cron jobs to be specified in setting in the form below
```yaml
custom_crons:
- server_type: app-servers
time: "* * * * *"
job: echo "test" >> /some/path.log
```
> Setup cron for Parsoid-restart, runJobs, and custom commands

- src/roles/saml/templates/samlLocalSettings.php.j2
Allow API access despite SAML SSO. Add configuration like:
```yaml
allow_skip_saml_users:
James: ["192.168.56.62","23.243.32.123"]
Daren: ["*"]
Lauren:
- "192.54.43.13"
- "3.3.2.1"
Willa:
- "192.169.34.23"
```
Alternatively, allow all users from all IP addresses:
```yaml
allow_skip_saml_users:
__allusers: ["*"]
```
Then you can hit the API from the command line or any other external source by adding the `X-SKIP-SAML` header (which tells the system to not use SAML). Per the config above you can limit this to specific users and IP addresses. 
An example of accessing the API in Bash looks like:
```bash
#!/usr/bin/env bash
#Needs curl and jq
USERNAME="Someuser"
USERPASS="1234"
QUERY="action=query&list=recentchanges&format=json"
WIKIAPI="https://example.com/wiki/api.php"
cookie_jar="wikicj" …
```
> Allow access to API despite SAML SSO

- src/roles/mediawiki/templates/LocalSettings.php.j2
Need to specify that MediaWiki should use the `X-Forwarded-For` header sent from HAProxy when recording user IP addresses. This is done via [`$wgUsePrivateIPs`](https://www.mediawiki.org/wiki/Manual:$wgUsePrivateIPs) and [`$wgSquidServersNoPurge`](https://www.mediawiki.org/wiki/Manual:$wgSquidServersNoPurge).
Closes #644
> Add wgUsePrivateIPs and list of load balancers

- config/core/MezaCoreExtensions.yml
SMW 2.5.2 should be released soon (perhaps today), but as it stands SRF does not work properly with SMW 2.5.1 and we need to make meza fully functional. Use the 2.5.x branch, which in composer is specified with `2.5.x-dev`.
Also more tightly specify SRF version, e.g. `2.4.x` (which allows `2.4.0` through `2.4.999+`) instead of `~2.0` (which allows `2.0` through `2.999+`). Bugfix changes (the third digit in [semantic versioning](http://semver.org/)) are much less likely to cause breaking changes than the minor version changes (second digit), even though technically minor version changes shouldn't cause breaking changes.
Addresses #636
> Use SMW 2.5.x branch until 2.5.2 release, specify SRF 2.4.x

- src/roles/base/tasks/main.yml
- src/roles/cron/tasks/main.yml
When running a deploy with `--overwrite`, databases/wikis are in an indeterminate state through the process. They may exist but be old data, they may not exist, they may have new data but not be updated yet (e.g. update.php), or they may be in the final state. Running cron jobs like `runJobs.php` could have strange results, and could possibly cause damage. For now, fully disable cron during `--overwrite` deploys. Note that at some point if we have the ability to just overwrite certain wikis this heavy-handed method may need to be rethought.
> Disable cron jobs when running an overwriting import

- src/roles/init-controller-config/templates/vars.yml.j2
- src/roles/mediawiki/templates/LocalSettings.php.j2
Both `enable_all_wiki_email` and `enable_wiki_emails` were being used. Just use `enable_wiki_emails` since it's used in more places.
> Fix discrepant email settings

- config/core/MezaCoreExtensions.yml
A PR [1] was submitted to Extension:SimpleMathJax from the fork we use [2] to fix some issues that Meza needed. Meza then used the fork's `master` branch. When the PR was merged with other changes, the master branch of our fork was modified in such a way that the code broke. In the image below, the commit indicated by the arrow was the version being used by Meza for the last few weeks. The red-circled commits were our changes. Upon merge the other changes were merged in and master changed. This caused the daily build to fail [3].
This has been resolved by specifying the git commit hash to use from our fork. Ultimately a release tag would be better.
[1] jmnote/SimpleMathJax#7
[2] Our fork: https://github.com/jamesmontalvo3/SimpleMathJax
[3] …
> Specify commit for SimpleMathJax

- src/roles/saml/tasks/main.yml
The current latest release of Extension:SimpleSamlAuth fails to properly create new users in MW 1.27 due to lack of `global $wgVersion` declaration. A later commit does address this. Rather than use the release, explicitly checkout a later commit until a release is defined.
Ref: https://github.com/jornane/mwSimpleSamlAuth/issues/31#issuecomment-302759940
> Extension:SimpleSamlAuth latest release fail to create user

- src/roles/composer/tasks/main.yml
Composer was installed a long time ago on the Docker images used on Travis CI. Composer cache-clearing required. For now just clear cache if Composer version updates. Perhaps it would be better to figure out how to read the age of the cache and update only after a certain age. This should work for now, though, and should get master to stop failing builds.
> Fix composer cache issues on Travis CI

- src/roles/mediawiki/templates/LocalSettings.php.j2
Else get:
> Warning: inet_pton(): Unrecognized address localhost in /opt/htdocs/mediawiki/vendor/wikimedia/ip-set/src/IPSet.php on line 132
Closes #665
> Remove 'localhost' as valid $wgSquidServersNoPurge

- src/playbooks/site.yml
- src/roles/base/tasks/main.yml
- src/roles/haproxy/tasks/main.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/mediawiki/templates/LocalSettings.php.j2
- src/roles/saml/templates/authsources.php.j2
Address issues:
* Close #697: Allow sp_entity_id to be in secret or public
* Close #699: Fix errors when emptying empty crontab
* Close #700: Import primary wiki first
* Close #683: Create method for external load balancer
* Fix common name on self-signed certificate
> Misc: saml config, empty crontab fix, primewiki first, external load balancer

- src/roles/create-wiki-wrapper/tasks/main.yml
- src/scripts/elastic-rebuild-all.sh
- src/scripts/smw-rebuild-all.sh
Previously, `meza create wiki <env>` was running rebuild smw-data and search-index on all wikis.
Also:
* Close #590
> On create-wiki, limit build smw and search data to new wiki

- src/playbooks/backup.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/verify-wiki/tasks/main.yml
When a new wiki DB is created or dropped-and-reimported, rebuild data. Else, skip.
Closes #695
> Limit rebuild SMW and search index data to when DB has been imported

- src/roles/htdocs/tasks/main.yml
- src/roles/htdocs/templates/.htaccess.j2
- src/roles/htdocs/templates/office.html.j2
When you click a link in a Microsoft Office document, it pre-fetches the link and if it gets a 3xx response code (redirect) then it follows the redirect until it finds a 2xx (success) or 4xx (failure) response code. If a 2xx code it then opens the default web browser to the pre-fetched link (i.e. not to the link you clicked on, but to the redirected link). If it gets a 4xx response then MS Office gives you a popup saying it's a bad link.
When this is mixed with SimpleSamlPhp, errors occur. SSP forwards requests that do not have valid sessions on to the Identity Provider (IdP) configured for the wiki. This may result in multiple redirects, which MS Office follows. When MS Office gets to a 2xx response code somewhere in the IdP it determines it's a valid link and allows the MS Office user …
> Rewrite rule to thwart MS-Office pre-fetching, which breaks SSO

- src/roles/revoke-keys/tasks/main.yml
- src/roles/verify-wiki/tasks/main.yml
Variable not put within `vars` when attempting to include role. This "worked" in Ansible 2.3.0 but should not have. 2.3.1 "broke" it. Fixing.
Closes #754
> Fix improperly assigned variable; noticed when Ansible 2.3.0-->2.3.1

- config/core/defaults.yml
- src/playbooks/site.yml
- src/roles/haproxy/templates/haproxy.cfg.j2
- src/roles/mediawiki/templates/LocalSettings.php.j2
- src/roles/parsoid-settings/templates/localsettings.js.j2
- src/scripts/ssh-users/transfer-master-key.sh
Parsoid on a separate server from MediaWiki was having issues due to `parsoidConfig.serverInterface = '127.0.0.1';` always being set in `localsettings.js`. This is not correct when Parsoid is separate from MediaWiki.
Also, it is required to load-balance Parsoid so that MediaWiki can have one Parsoid endpoint. The same is true for MediaWiki, so Parsoid can have one endpoint for it. Two internal-only load balancing schemes were created.
> Properly set server interface for parsoid; load balance

- .gitattributes
- .gitignore
- Vagrantfile
- config/core/defaults.yml
- src/playbooks/getdocker.yml
- src/playbooks/site.yml
- src/roles/apache-php/tasks/main.yml
- src/roles/apache-php/tasks/php.yml
- src/roles/apache-php/tasks/profiling.yml
- src/roles/apache-php/templates/httpd.conf.j2
- src/roles/apache-php/templates/mongo.repo.j2
- src/roles/apache-php/templates/mongod.conf.j2
- src/roles/apache-php/templates/php.ini.j2
- src/roles/apache-php/templates/xhgui.config.php.j2
- src/roles/base/tasks/main.yml
- src/roles/haproxy/tasks/main.yml
- src/roles/haproxy/templates/haproxy.cfg.j2
- src/roles/mediawiki/templates/LocalSettings.php.j2
- src/roles/memcached/tasks/main.yml
- src/roles/nodejs/tasks/main.yml
- src/roles/parsoid-settings/templates/localsettings.js.j2
- src/scripts/ssh-users/setup-minion-user.sh
- src/scripts/ssh-users/transfer-master-key.sh
- vagrantconf.default.yml
This pull request includes several concepts which have each been repackaged into individual commits to keep them separate. They were broken out because they were initially added in order to determine how to fix MediaWiki's extreme slowness when having multiple app servers. That issue is solved in the next pull request.
Previously localsettings.js had `parsoidConfig.serverInterface = '127.0.0.1';` in all cases. This breaks in a multi-server setup, since Parsoid needs to bind to it's servers IP address. Also, in multi-parsoid setups we need a way to load balance between the parsoids, so that is added to HAProxy. Finally, MediaWiki also needs to be available load-balanced to Parsoid but Parsoid can't go through HTTPS (at this time) so that entry is in HAProxy now, too.
By adding the …
> Several changes in the process of figuring out slow app server issue

- config/core/defaults.yml
- src/roles/apache-php/tasks/main.yml
- src/roles/apache-php/tasks/profiling.yml
- src/roles/apache-php/templates/httpd.conf.j2
- src/roles/apache-php/templates/php.ini.j2
- src/roles/haproxy/tasks/main.yml
- src/roles/mediawiki/templates/LocalSettings.php.j2
Prior to this pull request we have:
1. XHProf: PHP extension that does the profiling heavy-lifting
2. MediaWiki `$wgProfiler['class'] = 'ProfilerXhprof';` to perform the profiling
3. XHProf UI to display the output of (2)
4. XHGui to be a better UI
5. XHGui `header.php` prepended to all page loads via Apache to perform the profiling
We only want to keep 1, 4, and 5. Removing 2 and 3 also means removing Graphviz which was used to create callgraphs.
> Clean up PHP profiling to only use XHGui

- config/core/defaults.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/mediawiki/templates/LocalSettings.php.j2
- src/roles/verify-wiki/tasks/main.yml
Having multiple application servers (mediawiki servers) was showing serious lag if localization cache was in database. Slow query log showed LCStoreDB::finishWrite as the major culprit method. Also MediaWiki::restInPeace, but to a lesser extent. 
Essentially this fix just adds the following to `LocalSettings.php`:
```php
$wgCacheDirectory = '/some/directory';
```
I believe the issue is due to the app servers applying locks in the database when trying to update the cache. By instead using a directory the app servers are all using their own cache, rather than sharing one across all app servers. This duplication is okay because the localization cache is not updated frequently...really only when MediaWiki or extensions are upgraded.
> Use file cache for localization, else serious lag when multi-app

- src/roles/haproxy/tasks/main.yml
* Fix error where port 1936 gets opened even when HAProxy stats are not enabled
* Forcibly close port 1936 if HAProxy stats are not enabled (just in case it got opened from being enabled at one point)
> Close port 1936 if HAProxy stats disabled; improve task naming

- src/roles/mediawiki/templates/LocalSettings.php.j2
Parsoid permissions (MW granting read/write to Parsoid) were not configured to work if Parsoid wasn't on the same server as MW _and_ MW wasn't wide open permissions (e.g. allow anon read). Fixed it.
> Fix permissions to allow Parsoid to work in _closed_ multi-server setups

- src/roles/verify-wiki/tasks/init-wiki.yml
Wasn't properly adding `sysop` and `bureaucrat`.
> Fix createAndPromote.php of User:Admin on Demo Wiki

- Vagrantfile
This change will make it so `vagrant up` does a little bit _less_: It will no longer actually run the `deploy` command for you. You'll need to SSH into the VM (`vagrant ssh`) then run `sudo meza deploy vagrant` manually. The reason for this is (1) you have to do it this way anyway for multi-VM situations due to limitations of Vagrant and (2) auto-deploying prevents you from doing anything pre-deploy. This limits dev capabilities. Additionally, (3) if anything goes wrong with `deploy`, then it's harder to explain to new users how to run `deploy` again (versus just "up arrow, hit enter, to run again").
So, the full install process is now:
1. install git, vagrant, virtualbox
2. `git clone https://github.com/enterprisemediawiki/meza`
3. `cd meza`
4. Optional: `cp vagrantconf.default.yml …
> Remove 'meza deploy' from 'vagrant up' command; do it after 'vagrant up'

- src/roles/apache-php/templates/httpd.conf.j2
Breaking change in 14154d26908739bb3eda03525d091c56a5cad139 (merged in #785). Set `ServerName` to non-problematic value.
> Change of httpd ServerName specification broke SAML; fixit

- config/core/defaults.yml
- src/roles/backup-db-wikis/tasks/main.yml
- src/roles/database/tasks/secure-installation.yml
- src/roles/remote-mysqldump/tasks/main.yml
- src/roles/sql-backup-cleanup/tasks/main.yml
- src/roles/update.php/tasks/main.yml
- tests/docker/backup-to-remote.setup.sh
Closes #772
* Better tagging. Tags `update.php` and `update.php-backup`
* Don't put `update.php` backups in `m_tmp`. Send them directly from DB-master to backups server using role `remote-mysqldump`
* Provide option `do_cleanup_sql_backup` that will always keep only the latest SQL backup file. All older files will be deleted.
> Better handling of SQL backup files

- Vagrantfile
- config/core/defaults.yml
- src/playbooks/site.yml
- src/roles/base/handlers/main.yml
- src/roles/base/tasks/main.yml
- src/roles/base/templates/ssh_config.j2
- src/roles/base/templates/sshd_config.j2
- tests/docker/backup-to-remote.setup.sh
Reapply SSH safe ciphers and algorithms as were originally applied in #392 but were lost when switching to Ansible.
* Add `ssh_config.j2` and `sshd_config.j2` templates
* Add defaults for `sshd_config_UsePAM: "yes"` and `sshd_config_PasswordAuthentication: "yes"` for good secure config, but allow override for testing. Several tests and Vagrantfile require updating these defaults for now.
* Changed order of when `role:init-controller-config` is run so it happens before `role:base`, such that config vars are picked up if `init-controller-config` causes any changes. In particular, if secret config has a public config repo set, need to run `init-controller-config` to pull that public config repo.
Closes #703
> Configuration for SSH to limit to safe ciphers and algorithms

- config/core/defaults.yml
- src/roles/database/templates/my.cnf.j2
I don't know if it's worth coding this 'feature', so I thought to add a line of comment into the template. Monolith environments with only 1 GB of memory can fail because MySQL takes up a lot of it before Parsoid gets installed.  If the performance schema is disabled, it shouldn't affect an intentionally low power "demo" or "development" environment, but will allow Meza deploy to complete.  Feel free to decline and tell me that this should be an 'issue' instead.
> Add setting to disable MariaDB performance_schema 

- manual/installing-additional-extensions.md
The Widgets module is similar to VisualEditor in that it requires a `git submodule update --init` in the module's directory.  So, this update reflects an actual case that a user might wish to implement.  Preserves the note about VisualEditor being installed by default.
> Update installing additional extensions.

- src/playbooks/rebuild-smw-and-index.yml
Without this, if specifying a particular tag it would skip `set-vars`.
> Need to always run set-vars when rebuilding data

- src/roles/nodejs/tasks/main.yml
- src/roles/nodejs/tasks/setup-RedHat.yml
RHEL upgrade from 7.3 to 7.4 added package `http-parser` to the RHEL base repository, which caused it to be removed from the EPEL repository. This means that any pre-7.4 OSes (RHEL or CentOS) using EPEL to get Node.js (and probably other things) will no longer function due to missing the `http-parser` dependency. When CentOS 7.4 comes out it will have http-parser in its base repo. To maintain functionality for all machines running RHEL/CentOS 7.0-7.3 we need to manually install http-parser.
Also note that this is done in two places: directly in the `nodejs` role's `main.yml` as well as in the `setup-RedHat.yml` file. The `setup-RedHat.yml` file is not currently in use since meza was simplified to only care about install the meza-required version of Node.js (6.x) rather than maintaining …
> RHEL/CentOS 7.4 EPEL change, Node.js fix

- src/roles/base/templates/config.php.j2
- src/roles/base/templates/config.sh.j2
- src/roles/set-vars/tasks/main.yml
Previously had `deploy_vars` as a variable that was intended to be in `secret.yml`. This would look like:
```yaml
deploy_vars:
my_var: "some value"
another_var: "another value"
```
These values would then get written to `/opt/.deploy-meza/config.sh` like:
```bash
my_var="some value"
another_var="another value"
```
and to `config.php` like:
```php
$my_var = "some value";
$another_var = "another value";
```
However, this did not allow for such values to be written in `public.yml`. Additionally, `secret.yml` functions as both a place for secret information (DB passwords, etc) as well as server-specific info. In order to allow more deploy-vars functionality, the following change was made.
Deploy vars should be set in `secret.yml` with `secret_deploy_vars` variable, like:
```yaml …
```
> Allow deploy vars in public.yml and new env/<env-name>.yml

- config/core/MezaCoreExtensions.yml
SemanticCompoundQueries is no longer maintained on Gerrit. Get it from GitHub. Initially tried to load this _without_ Composer since it looked like the `composer.json` file for this extension wasn't actually loading any dependencies. That didn't work, so switched to using Composer.
> Get SemanticCompoundQueries from GitHub

- config/core/MezaCoreExtensions.yml
- src/playbooks/elasticsearch-upgrade.yml
This commit [1] to Extension:WhoIsWatching removes ability to load the extension in the legacy style (e.g. `require_once "$IP/path/to/ExtensionName.php"`). Use `wfLoadExtension`/`extension.json` loading instead.
[1] https://phabricator.wikimedia.org/rEWIWe5015a5ff822d2099be95f121afe630a81c0a69a
> Extension:WhoIsWatching no longer uses legacy loading method

- src/scripts/meza.py
This is a quick fix for #874. It does *not* close that issue, since it is not understood why that issue started in the first place.
The issue was that `sudo -u meza-ansible <command here>` was failing when used in a Python script within an `os.system( ... )` call. For some reason `su meza-ansible -c "<command here>"` works.
This is a quick fix for that issue.
> Change privilege escalation from sudo to su in meza.py; addresses #874

- manual/SettingUpVirtualBox.md
Fix links for adding wikis in `SettingUpVirtualBox.md`. Link was to `manual/AddingWikis.md` but this does not work (404 error) since a URL with `manual/manual/AddingWikis.md` is created. Either `./AddingWikis.md` or `AddingWikis.md` works since `AddingWikis.md` is in the same directory as `SettingUpVirtualBox.md`. Links in `README.md` need to have the `manual/` prefix.
This PR supersedes #883.
> Relative link fix in markdown file

- tests/integration/wiki-check.sh
Elasticsearch testing changed:
```
WAS: http://127.0.0.1:9200/_stats/index,store
IS:  http://127.0.0.1:9200/_stats/store
```
The `index` option is not in any documentation I could find. It wasn't causing any issues until Elasticsearch 5.x. Removing now to keep testing consistent across versions.
> Elasticsearch test unnecessary option which is invalid in ES 5.x

- src/scripts/meza.py
Python's `sys.exit` doesn't seem to respect return codes other than int 0 and 1 (and maybe 2). Explicitly return int 0 or int 1.
> Fix return (exit) codes returned by meza.py

- src/roles/mediawiki/templates/LocalSettings.php.j2
If file required/included earlier, won't get pulled in again. This could break something the second time `require_once` is used, if the second time isn't in the same context as the first (so variables you think you're including don't get included).
> require_once isn't great for settings; won't get pulled in a second time

- src/roles/saml/files/NonMediaWikiSimpleSamlAuth.php
- src/roles/saml/tasks/main.yml
Forked Extension:SimpleSamlAuth and fixed namespace issue that was creating many syslog messages. Also updated `NonMediaWikiSimpleSamlAuth.php` for the same fix.
> Saml syslog fix

- src/roles/saml/tasks/main.yml
Currently tracking `master` of SimpleSamlPhp. Pulling new commits could cause breaking changes.
> Specify version of SimpleSamlPhp to avoid breaking changes

- src/playbooks/site.yml
- src/roles/meza-log/tasks/main.yml
When building docker images you can't enable or use any services (as far as I understand). As such, two Ansible plays that use MySQL and Cron need to be disabled during image building.
> Fixes for building docker images

- src/playbooks/site.yml
Sometimes meza-ansible's cron gets blanked. I thought this was because when `deploy` is run with the `base` tag specified (`--tags base`) then `meza-ansible`'s cron may be disabled without reenabling it in the `cron` role. However, this should only be the case when doing a `deploy` with the `--overwrite` option. 
At this point I'm not sure if this PR is necessary, or what has caused the blanking of the cron. More investigation needed.
> Add tag 'always' to cron so it always is reset

- src/roles/apache-php/tasks/profiling.yml
Currently specifying `master`. This breaks with never version of xhgui. Specify an actual version.
> Specify xhgui version; else breakage with master

- config/core/defaults.yml
1.28.3 is the most recent release.
The REL1_28 branch is not supported anymore, so we should upgrade/work on the REL1_29 and REL1_30 branches.  However, for anyone using REL1_28, you're going to want the patched 1.28.3 release
* https://releases.wikimedia.org/mediawiki/1.28/
* https://www.mediawiki.org/wiki/Release_notes/1.28#MediaWiki_1.28.3
> Bump REL1_28 version for security release.

- src/roles/mediawiki/templates/LocalSettings.php.j2
This setting is in core since REL1_20
Removes $wgEnableMWSuggest from LocalSettings.php.j2 because it's not needed. https://www.mediawiki.org/wiki/Manual:$wgEnableMWSuggest
If you want to turn OFF autosuggest, you can use https://www.mediawiki.org/wiki/Manual:$wgEnableOpenSearchSuggest
> wgEnableMWSuggest was deprecated in REL1_20

- src/roles/mediawiki/tasks/main.yml
Fixes issue from #947, which applied tags (e.g. `latest`) to including `meza_core_extensions.yml` and `meza_local_extensions.yml`. However, if `--skip-tags latest` is used, this will cause these files not to be included, which has effects other than just pulling new versions. Instead, this PR switches the tags to `always` for including these files. This is pretty minimal efficiency loss.
> Hotfix last commit: need meza_core_extensions even when not doing latest

- config/core/MezaCoreExtensions.yml
Extension:ReplaceText was set to default meza version, tracking branch `REL1_27`. We want features from the new `1.4` tag.
> Set specific version of Extension:ReplaceText (v1.4)

- src/roles/create-wiki-wrapper/tasks/main.yml
Fix for failures when using standard method of creating a wiki (with prompts) versus without prompts.
Closes #954
> Fix create-wiki prompt failures; Fix for #954

- Vagrantfile
On first `vagrant up` it needs to generate SSH keys. Something changed in Vagrant regarding quoting.
> Fix for generating SSH keys for vagrant

- src/roles/mediawiki/templates/LocalSettings.php.j2
This "default" **anon-read** setup allows for a public deploy of Meza
without surprisingly allowing anonymous spammers to edit the Talk namespace.
In meza, the 'talk' permission is added to MediaWiki via the [TalkRight extension](https://www.mediawiki.org/wiki/Extension:TalkRight). To properly configure the TalkRight extension, setup a group such as "Commentators" and give them the "talk" privilege.
Other meza auth types (user-read, viewer-read) give the talk right to the groups 'user' and 'Viewer' respectively.
> REMOVE talk privilege for anonymous

- src/roles/init-controller-config/templates/public.yml.j2
- src/roles/mediawiki/templates/LocalSettings.php.j2
**Anonymous edit** is dangerous on the public web as a default. Your wiki will instantly be spammed with ads for Viagra and many more unmentionable things.  This changes the default auth_type in Meza to **Anonymous read**
1. Deploy a new monolith
1. Try to edit a page anonymously (no login). You should be denied.
1. Try to create an account without logging in; the "create account" link should not be displayed.
1. Try to create an account by directly accessing the **CreateAccount** Special Page: e.g. https://demo.qualitybox.us/wiki/Special:CreateAccount; You should be denied.
1. Login as an Admin user, and visit the CreateAccount special page. You should be able to create an account for a user.
* Sets up meza_auth_type: "anon-read" in …
> switch default to anonymous read from anonymous edit

- config/core/defaults.yml
- src/roles/mediawiki/templates/LocalSettings.php.j2
Allow specifying timezone with `m_timezone`. This supersedes #925. Also, this content is part of the mega-commit b19011ca3b12aebf1bebd6ee977b70c6d8871553, but that is not yet part of `master`. 
Example:
```yaml
m_timezone: "America/New_York"
```
> Allow specifying timezone

- config/core/ansible.cfg
Error was:
> Authentication or permission failure. In some cases, you may have been able to
authenticate and did not have permissions on the target directory. Consider
changing the remote tmp path in ansible.cfg to a path rooted in "/tmp". Failed
command was: ( umask 77 && mkdir -p "` echo
~None/.ansible/tmp/ansible-tmp-1528404466.59-59697674326589 `" && echo
ansible-tmp-1528404466.59-59697674326589="` echo
~None/.ansible/tmp/ansible-tmp-1528404466.59-59697674326589 `" ), exited with
result 1
Ref: https://travis-ci.org/enterprisemediawiki/meza/jobs/389426664#L2839
Source of fix: https://github.com/ansible/ansible/issues/5725#issuecomment-118381617
> Fix for error in Travis CI due to temp dir permissions

- Vagrantfile
- config/core/defaults.yml
- src/roles/verify-wiki/tasks/main.yml
* Provide method to skip wikis when doing an `--overwrite` backup
* Bump Vagrant version of CentOS from 7.3 to 7.4
To skip wikis `iss` and `demo`, add the following to `public.yml`:
```yaml
wikis_to_skip_overwrite:
- iss
- demo
```
> Allow skipping wikis when performing an overwrite backup

- config/core/defaults.yml
- src/roles/mediawiki/templates/LocalSettings.php.j2
Allow specifying `wiki_id_redirects` like:
```yaml
wiki_id_redirects:
someid: demo
fake: real
```
This redirects `https://yourdomain.example.com/someid` to `https://yourdomain.example.com/demo`. Likewikewise for `fake` to `real`.
> Wiki ID redirects/aliases

- config/core/MezaCoreSkins.yml
- src/roles/init-controller-config/tasks/main.yml
- src/roles/init-controller-config/templates/MezaLocalSkins.yml.j2
- src/roles/mediawiki/tasks/main.yml
- src/roles/mediawiki/templates/Extensions.php.j2
- src/roles/mediawiki/templates/LocalSettings.php.j2
- src/roles/mediawiki/templates/composer.local.json.j2
This pull request is an update of PR #930. It splits out meza core skins into a `MezaCoreSkins.yml` file. It also provides the ability for an administrator to add additional MediaWiki skins via a `MezaLocalSkins.yml` file. All of this work was original written by @freephile. Thanks for the great work.
* MediaWiki core skins are specified in `/opt/meza/config/core/MezaCoreSkins.yml`
* Locally added skins are specified in `/opt/conf-meza/public/MezaLocalSkins.yml`
* Closes #819 
> Allow adding core and additional Mediawiki skins.

- Vagrantfile
Makes sure `/opt/meza` isn't world writable when using Vagrant. Ansible doesn't like this.
* None
None.
> Vagrant mode fix

- src/roles/meza-log/templates/server-performance.sh.j2
This change normalizes the cpu load values based on the number of cpus in the machine. So if you have a 1-minute load average of 1.0 on a machine with 4 cpus, your load average (normalized) would be 0.25. Since we plot based on a 0-100 scale, it makes sense to normalize to 1 (which is then multiplied by 100 for the plot).
* Addresses #866
> Normalize load

- src/roles/mediawiki/tasks/main.yml
[Extension:SyntaxHighlight]() requires Python 3 for MediaWiki 1.31+. Python 3.5 added from IUS repository, in path via `python3`. This maintains Python 2.7.x as `python`.
* None
- None
> Add python3 for Extension:SyntaxHighlight in MW1.31+

- config/core/MezaCoreExtensions.yml
Same as  #1001, but for `master` branch. This will be cherry-picked to `27.x` branch after passing.
> Make Approved Revs use official repo, v1.0-alpha

- src/roles/elasticsearch/tasks/main.yml
- src/roles/elasticsearch/templates/elasticsearch.yml.j2
Upgrading to Meza 31.x caused /var partition to fill up due to log files being added to /var/log/elasticsearch.
* Change location of Elasticsearch logs
None
> Move elasticsearch logs to /opt/data-meza instead of /var/log

- config/core/MezaCoreExtensions.yml
* Extension:HeaderFooter was specifying branch `master`. Make it specify the release tag for the tip of that branch (as of this writing) so upgrades to HeaderFooter don't automatically get pulled into Meza.
None
- None
> Specify Extension:HeaderFooter version 2.2.1

- config/core/MezaCoreExtensions.yml
* VisualEditor has visual diff capability. By setting `$wgVisualEditorEnableDiffPage = true;` this can be added as an option to all diff pages (wikitext diff will still show by default).
* None
> Show visual diff option on all diff pages

- src/roles/mediawiki/templates/LocalSettings.php.j2
Some time ago I believe there was a wgVisualEditorNamespaces, however it's not found in the current MW codebase. The correct array variable is $wgVisualEditorAvailableNamespaces (which defaults to $wgContentNamespaces) https://codesearch.wmflabs.org/search/?q=wgVisualEditorAvailableNamespaces&i=nope&files=&repos=
A single variable name
I want to extend the namespaces, so I discovered that the current setting is not having any effect.
* None that I know of
> fix variable wgVisualEditorAvailableNamespaces

- config/core/defaults.yml
- src/roles/apache-php/templates/php.ini.j2
Changes to the php.ini to optimize PHP's Opcache
Introduces new config called 'm_mode' (default 'production').
meza mode (development or production)
1. production being as performant and secure as possible
1. development being less secure and providing optional features useful for dev
> Feature optimize opcache

- src/roles/htdocs/files/ServerPerformance/data-sample.php
- src/roles/htdocs/files/ServerPerformance/opcache.php
Added opcache.php (and data-sample.php) from https://github.com/rlerdorf/opcache-status.git into the ServerPerformance files. (htdocs role)
However, I changed the opcache.php script to use our already-in-use jquery and d3 in the ServerPerformance directory.  Rasmus' version pulls files from cloudflare which is not ideal. In a quick test of functionality, it seems to be happy with js library versions.
<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.0.1/d3.v3.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
changed to 
./js/d3.js  (v 3.5.14)
./js/jquery-3.1.0.min.js
data-sample.php just provides a mock implementation of the opcache functions in case opcache is disabled - so you get a chart instead of an error. There are no external …
> Add Opcache status monitor

- src/roles/saml/tasks/main.yml
* Get latest version of SimpleSamlPhp. Seeing some issues with accessing wikis with Chrome when using SAML. Hoping this will solve it.
* None
- None
> Bump SimpleSamlPhp from 1.15.4 to 1.16.1

- config/core/defaults.yml
* Bump MW version from 1.31.0 to 1.31.1 after last night's release.
None
> Bump to MW 1.31.1

- src/roles/apache-php/tasks/php.yml
- src/roles/apache-php/templates/10-opcache.ini.j2
Makes Meza control the `/etc/php.d/10-opcache.ini` file, which was overriding changes to opcache settings in `/etc/php.ini`. For now the `10-opcache.ini` file is essentially blank. We could choose to move all the opcache settings out of `php.ini` and into that file if that seemed cleaner.
* Ref this comment: https://github.com/enterprisemediawiki/meza/pull/1019#issuecomment-424833166
- None
> Make Meza control 10-opcache.ini

- src/roles/base-config-scripts/templates/config.php.j2
* Optional variables not currently in any tests incorrect syntax in `/opt/.deploy-meza/config.php`
* None
- None
> Fix for config.php syntax error

- src/scripts/autodeployer/check-for-changes.sh
* Autodeployer check for all commits to Meza not using Meza before/after commits...using public config's commits. Fixit.
* None
None
> Fix Meza git commit hashes for autodeployer notifications

- src/scripts/autodeployer/do-deploy.sh
* `do-deploy.sh` not picking up the same vars for Slack notifications as `check-for-changes.sh` is. Fixit.
* None
None.
> Make do-deploy.sh use autodeployer slack vars

- config/core/MezaCoreExtensions.yml
* Bump PageForms one more commit to get fix for tree input in SMW 3.0
* SemanticMediaWiki/SemanticMediaWiki#3492 (not really an SMW issue, but was filed there)
None
> Update PageForms to get fix for tree input in SMW 3.0

- RELEASE-NOTES.md
* Add release notes prior to Meza 31.1.0
* None
> Update RELEASE-NOTES.md for Meza 31.1.0

- src/roles/database/tasks/setup-RedHat.yml
* Omit `enablerepo` if empty (breaks in latest Ansible)
* With `yum` module, do `name: "{{ mysql_packages }}"` rather than looping over all packages with `with_items "{{ mysql_packages }}"`. This change will need to be replicated in many other places.
* ref: https://github.com/geerlingguy/ansible-role-mysql/commit/e65af067319eb0a6d273e0561428d2ece2f2f899
N/A
> Update enablerepo functionality to work better with Ansible 2.7.0

- src/roles/mediawiki/tasks/main.yml
Upgrade CirrusSearch metastore index before (re)building search indices, which makes sense. Older versions of MW tolerated it being later, but this is a required change for MW master branch. Pulling back into MW 1.31 to minimize differences between MW master and 1.31.x
None
None
> Upgrade CirrusSearch metastore before (re)indexing

- src/roles/parsoid-settings/templates/config.yaml.j2
Set `strictAcceptCheck = false` in Parsoid `config.yaml`. As specified in the comments, it is unknown why this is required in MW master, but it apparently is. Rolling this into Meza 31.x branch to simplify differences between MW master and MW 1.31.x.
None
None
> Set Parsoid strictAcceptCheck = false

- config/core/defaults.yml
- src/roles/apache-php/tasks/php.yml
Bump PHP from 7.0 to 7.1, and include checks that make sure old versions of PHP are removed.
None
> Bump PHP 7.0 to 7.1; include checks to remove old PHP versions

- config/core/MezaCoreExtensions.yml
Update Extension:Maps to 6.0.1
Maps 5.6.x supports MW 1.27 - 1.31. Maps 6.0.x supports MW 1.31 - 1.32. Also, Maps 6.x requires PHP 7.1+, hence the previous upgrade of PHP.
Ref: https://github.com/JeroenDeDauw/Maps/blob/master/INSTALL.md#platform-compatibility-and-release-status
None
> Update Extension:Maps to 6.0.1

- config/core/MezaCoreExtensions.yml
- config/core/defaults.yml
* Add `wfLoadExtension( 'SemanticResultFormats' );` despite the fact that it's loaded with Composer
* Bump Maps from 6.0.1 to 6.0.3
* Add a comment to maps, since it uses `wfLoadExtension` in the same manner
* None
> Need to use wfLoadExtension on SemanticResultFormats; Also bump Maps version

- config/core/MezaCoreExtensions.yml
* Datatransfer version from 1.0 --> release branch
None
None
> DataTransfer 1.0 doesn't have fixes for MW 1.31, use release branch instead

- config/core/MezaCoreExtensions.yml
WatchAnalytics has been tracking `master` branch. Instead make it track a specific version, `0.1.0`.
None
None
> Change extensions from master branch to tags

- config/core/MezaCoreExtensions.yml
- config/core/MezaCoreSkins.yml
- src/roles/init-controller-config/templates/MezaLocalSkins.yml.j2
- src/roles/mediawiki/tasks/main.yml
- src/roles/parsoid/tasks/main.yml
Per this riot.im chat [1], it was recommended that Meza use GitHub mirrors over Gerrit repos. Specifically, @tgr stated "it just works better (see e.g. the horrible issues vagrant had with cloning from gerrit: https://phabricator.wikimedia.org/T152801)" and "Gerrit going crazy when you have too many pubkeys in your local SSH agent".
* None specifically, but this may help reduce the number of failures due to cloning from Gerrit. This mostly impacts CI, since such intermittent failures _appear_ to happen more when many deploys occur simultaneously in parallel tests. _Perhaps_ Gerrit is less stable than GitHub and this will reduce intermittent failures. However, it's possible that by putting all the load onto GitHub versus splitting some load onto GitHub and some onto Gerrit may make …
> Use GitHub mirrors for Gerrit repos

- RELEASE-NOTES.md
- config/core/MezaCoreExtensions.yml
* See v31.2.1 and v31.2.2 release notes
* Closes None
* Addresses None
- [X ] None
> Bump WatchAnalytics to 2.0.0; update Meza release notes for 31.2.2

- src/roles/meza-log/templates/server-performance.sh.j2
This fixes #1062.  `insert_sql` should probably be initialized with printf, as well.
> Add BEGIN rules to awk scripts

- src/roles/apache-php/templates/php.ini.j2
- src/roles/base/tasks/main.yml
- src/roles/cron/templates/meza-ansible.crontab.j2
- src/roles/mediawiki/templates/LocalSettings.php.j2
Things that generate lots of log files should go into sub-directories of `/opt/data-meza/logs`
* Closes #1076 
> Move prolific log files into sub-directories

- src/playbooks/site.yml
- src/scripts/meza.py
- tests/docker/import-from-alt-remote.setup.sh
* Remove forced (re)encryption of `secret.yml` on all deploys
* Remove initial encryption of `secret.yml` on `meza setup env`
* Remove `secret.yml` decryption in test `tests/docker/import-from-alt-remote.setup.sh`
* Add functions for encrypting/decrypting individual variables (recommended versus full file encryption):
* `meza maint encrypt_string <environment> <value-to-encrypt> <optional-var-name>`
* `meza maint decrypt_string <environment> <value-to-decrypt>`
Encrypting a value: `sudo meza maint encrypt_string <environment> supersecretpassword`
```
!vault |
$ANSIBLE_VAULT;1.1;AES256
61326233653335326662353765626565323363653033323664306332366163643236323238613466
6335373233663436653062633938613837306235666438660a356464623139646534653837303537 …
```
> Don't force-encrypt secret.yml and encourage variable-encryption

- src/roles/mediawiki/tasks/main.yml
* Don't create backups of LocalSettings.php which clobber the MediaWiki directory. Config should be git managed and that is backup enough
* Closes #710 
None
> Don't backup LocalSettings.php

- src/playbooks/getdocker.yml
- src/roles/apache-php/tasks/main.yml
- src/roles/apache-php/tasks/mssql_driver_for_php.yml
- src/roles/apache-php/tasks/php-debian.yml
- src/roles/apache-php/tasks/php-redhat.yml
- src/roles/apache-php/tasks/php.yml
- src/roles/base-extras/tasks/main.yml
- src/roles/base/tasks/main.yml
- src/roles/database/tasks/main.yml
- src/roles/database/tasks/replication.yml
- src/roles/database/tasks/setup-Debian.yml
- src/roles/gluster/tasks/setup-Debian.yml
- src/roles/gluster/tasks/setup-RedHat.yml
- src/roles/haproxy/tasks/main.yml
- src/roles/memcached/tasks/main.yml
- src/roles/nodejs/tasks/main.yml
- tests/deploys/setup-alt-source-backup.yml
* Don't use `with_items` for lists of packages (`yum`, `apt`, `package` modules)
* Remove use of `static`. Instead use `include_tasks` or `import_tasks` accordingly. See [1] and [2].
* Removed use of `result|skipped`. Instead do `result is skipped`
* Cleaned up logic in database role's `replication.yml`
* Closes #812
* Closes #1039
* Closes #1071
None
[1] https://docs.ansible.com/ansible/2.4/playbooks_reuse_includes.html
[2] https://docs.ansible.com/ansible/2.4/playbooks_reuse.html
> Cleanup deprecation warnings

- src/roles/apache-php/tasks/main.yml
- src/roles/apache-php/tasks/mssql_driver_for_php.yml
- src/roles/apache-php/tasks/php-redhat.yml
- src/roles/apache-php/tasks/php.yml
- src/roles/apache-php/tasks/profiling.yml
- src/roles/base-extras/tasks/main.yml
- src/roles/base/tasks/main.yml
- src/roles/cron/tasks/main.yml
- src/roles/database/tasks/setup-Debian.yml
- src/roles/elasticsearch/tasks/main.yml
- src/roles/gluster/tasks/setup-Debian.yml
- src/roles/imagemagick/tasks/main.yml
- tests/deploys/setup-alt-source-backup.yml
Change 'state: installed' to 'state: present' due to possible deprecation. #1071 shows that there's a deprecation warning if `state: installed` is used. This is not showing in current CI builds. There are other repositories (e.g. geerlingguy/ansible-role-firewall#48) that also are reporting this issue, so perhaps it's due to Ansible version. Anyway...switching to `present` won't hurt.
* Closes #1071
None
> Change 'state: installed' to 'state: present'

- config/core/defaults.yml
- src/roles/mediawiki/templates/LocalSettings.php.j2
- src/scripts/meza.py
* Creates a log of deploy starts, completions, and failures. Logs time, meza hash, public config hash, secret config hash, optional args (e.g. skip-tags)
* Also cleaned up an unrelated comment in LocalSettings
* Closes #726
* Closes #784 
> Log all deploy starts, completions, failures

- src/roles/gluster/defaults/main.yml
so I bumped the version to the latest number in the next major release: [4.1.6](https://github.com/gluster/glusterfs/tree/release-4.1/doc/release-notes) .  This should be reviewed critically because the Gluster project already has a 5.x release series and is planning the 6.x releases to start coming out next month (aka in February 2019).
change the version of Gluster installed.
* What new features / fixes are available?  
* What (if any) limitations are present in the newer release(s) compared to existing?
* What additional install steps are needed to satisfy installation on Debian? 
* What additional install steps are needed to satisfy installation on Ubuntu?
* Can we / Should we simply integrate the ansible roles produced by the Gluster project? -- or does that create too much glue …
> Gluster 3.5 does not exist (at least not in PPAs)

- src/roles/remote-mysqldump/tasks/main.yml
Addresses Issue #1095
* Adds 'backup' as a tag
Backups happen automatically for every `meza deploy`.
You can skip the actual database backup(s) with the deploy option `--skip-tags backup`
This can save considerable time and disk space during repeated failed deploys in development.
* Addresses #1095
> Make backup a tag so that you can at least skip it

- src/roles/remote-mysqldump/tasks/main.yml
Add debug to hopefully catch issue with wiki not on production yet but
backup server thinking that the wiki does exist on production, and
attempting to backup from it. This generates a meaningless SQL backup
file and then fails to generate the MediaWiki database.
The check for whether the new wiki's database exists on production is:
`mysqlshow "wiki_{{ wiki_id }}" | grep -v Wildcard | grep -o wiki_{{ wiki_id }}`
This should have a return code of zero if the database exists and
non-zero if it doesn't. When manually entering this on the server it
performs as expected. Hopefully adding this debug will shed some light
onto why it doesn't work in this production case.
Add a debug task
None
None
> Add debug to troubleshoot backup issue

- src/playbooks/delete-elasticsearch.yml
- src/roles/apache-php/tasks/php.yml
- src/roles/mediawiki/templates/composer.local.json.j2
Meza has historically used PEAR to install the `mail` and `net_smtp` packages per the docs at https://www.mediawiki.org/wiki/Manual:$wgSMTP. However, since MW 1.31 `pear/mail` is packaged with MW (in `composer.json`). In MW 1.32 `net_smtp` is also in `composer.json`. This commit is on a version of Meza using MW 1.31, so `pear/net_smtp` needs to be added via `composer.local.json`.
This change initiated by the fact that PEAR has had a security breach and is down. Ref iuscommunity-pkg/pear1u#3. Since PEAR isn't needed anymore we're removing its usage so builds will pass.
Additionally, I accidentally added a fix for `meza delete elasticsearch <environment>` to this commit. Variables were not properly being loaded. Rather than split this fix out and slow down getting builds passing again I'm …
> Remove PEAR, install net_smtp via composer.local.json

- config/defaults.yml
- src/playbooks/site.yml
- src/roles/apache-php/tasks/php-redhat.yml
- src/roles/apache-php/tasks/php.yml
- src/roles/haproxy/tasks/main.yml
- src/roles/haproxy/templates/haproxy.cfg.j2
- src/roles/netdata/handlers/main.yml
- src/roles/netdata/tasks/main.yml
Adds new role to install and configure the system monitor Netdata
restarts HAProxy when first installed
uses the static binary for Netdata so there are no dependencies to install or remove 
Once run, netdata should be available at https://example.com:20000 using the Meza self-signed cert
I've been unable to test this role because my local ~/src/meza `vagrant up` is broken and I haven't yet setup another checkout / system to test on.
In my trial usage of Netdata prior to writing this role, I've experienced somewhat 'noisy' alerts for tcp_listen_drops More information on handling this at https://wiki.freephile.org/wiki/Netdata
The default install will use 10-15MB of RAM to keep 24 hours worth of data. This can be adjusted in the conf file manually. If it turns out that we want to modify …
> add netdata monitor

- config/core/MezaCoreExtensions.yml
* Upgrades to WatchAnalytics 3.1.1
* None
> Bump WatchAnalytics to 3.1.1

- RELEASE-NOTES.md
WatchAnalytics to 3.1.2 for diff in PendingReviews, improved on-page banners
None
- Tag: 31.3.0
- Title: Meza 31.3.0
- Description: the Meza 31.3.0 section from RELEASE-NOTES.md
- `git fetch`
- `git checkout 31.x`
- `git merge tags/31.3.0 --ff-only`
- `git push origin 31.x`
- `* [https://github.com/enterprisemediawiki/meza/releases/tag/31.3.0 31.3.0]: WatchAnalytics to 3.1.2 for diff in PendingReviews, improved on-page banners`
- `Meza 31.3.0 released! WatchAnalytics to 3.1.2 for diff in PendingReviews, improved on-page banners. See details at https://github.com/enterprisemediawiki/meza/releases/tag/31.3.0`
> 31.3.0 release

- config/defaults.yml
- src/roles/htdocs/templates/robots.txt.j2
Introduction of new variable **`m_robots_rules`** which defaults to 'nocrawl' 
when m_robots_rules is equal to "nocrawl" then the simple robots.txt file will be
```
UserAgent: *
Disallow /
```
Any other value (such as 'crawl') will give the full "public" robots.txt file that we harvested from MediaWiki.org
Site owners need control over whether or not their site is indexed by search engines. While most public sites want to be indexed, some do not.  Even public sites may not want to be crawled until fully developed. Or a public 'staging' site will be 'nocrawl' while the production site will be 'crawl'. Obviously private wikis do not need to be crawled.
> new variable to effect crawling mode

- src/roles/imagemagick/tasks/main.yml
- src/roles/mediawiki/templates/LocalSettings.php.j2
This change is being considered due to intermittent failures getting Meza's own RPM with ImageMagick 7.0.3 instead of CentOS's base 6.7.8.9. This change would effectively downgrade ImageMagick for Meza in favor of a more stable version.
* Switches to using ImageMagick from CentOS 7 base repo rather than the `enterprisemediawiki/meza-packages` RPM
* Removes redundant `$wgUseImageMagick` and `$wgImageMagickConvertCommand` lines in `LocalSettings.php`
* Closes #1140
- None
> Use base ImageMagick rather than Meza's own RPM

- src/roles/nodejs/tasks/main.yml
When the parsoid host is not the controller, the src file is on the remote. Therefore, use remote_src: yes so that Ansible finds the file to copy.
Otherwise, this fails when the Parsoid host in inventory is not the same host as the controller.  In my example setup, I have two application servers and both are designated as Parsoid servers. One is the controller, the other app server is just an app server.
* Please provide
* a list
* of changes
* Closes #123456789 ???
* Addresses #987654321 ???
> Use 'remote_src' to copy Foo.xz

- src/roles/base/templates/sshd_config.j2
It's important to have the path correct. This affects, among other things, the ability to use SSHFS with your nodes.
Add conditional to vary the path to sftp-server depending on the OS
SSHFS and other SFTP-dependent operations fail without the correct path.
None
> The SFTP server is in a different location on Debian

- Vagrantfile
Vagrantfile set mount_options: ["dmode=755,fmode=755"] on Windows only. Doing this on Windows has no effect on the /opt/meza git repository, but doing it on Linux causes a change to all files adding +x, thus making many uncommitted changes.
* None
> Vagrantfile mount of /opt/meza needs to be different on Windows

- src/roles/saml/templates/samlLocalSettings.php.j2
* Merging contents of #1137 into `32.x`: "Fixes function syntax for IPv4matchesCIDR and IPv6matchesCIDR and an offset issue with explode."
None
> Merge contents of #1137 into 32.x branch

- config/core/defaults.yml
- src/playbooks/site.yml
- src/roles/apache-php/tasks/php.yml
- src/roles/haproxy/tasks/main.yml
- src/roles/init-controller-config/tasks/main.yml
- src/roles/remote-dir-check/tasks/main.yml
- src/roles/remote-mysqldump/tasks/main.yml
- src/roles/verify-wiki/tasks/main.yml
- src/scripts/getmeza.sh
- src/scripts/meza.py
- tests/docker/backup-to-remote.setup.sh
- tests/docker/import-from-alt-remote.setup.sh
Many commits in support of simplifying and securing importing data from remote server. Sudo no longer required on remote.
- af9eb52: Move vault pass file from meza-ansible home to /opt/conf-meza/vault
- 51f5e34: Re-enable PEAR package; not used by default, but used by MS SQL
- 527852f: Get public config repo as meza-ansible, not root
- 6ecc855: Create role remote-dir-check to verify if remote uploads dir exists
- 4d56386: Set permissions for /opt/conf-meza and /opt/conf-meza/public  …
- 68ac393: Add tags for rsync-uploads and better debug
- cd79230: Make checks for wiki existence during backup go to right server  …
- db6f805: Give undefined debug vars print vals
- 112317c: Handle undefined backups_server_db_dump
- 84bc0a0: Install mysql client on backup servers for direct mysqldump
- …
> Simplified and sudoless overwrite from source server

- .gitignore
- src/scripts/do-release.sh
Created `src/scripts/do-release.sh` which helps with the release process.
Do `src/scripts/do-release.sh` from within the Meza directory _when you're on the commit you want to use to make a release_. This will prompt for three inputs:
1. The previous release number (which it pre-fills with the last release)
2. The new release number you'd like to create
3. A one-line overview of the changes (list of changes shown to jog your memory)
This then edits `RELEASE-NOTES.md` and provides a list of actions to perform to complete the release. 
* None
- None (this doesn't really need to be documented on mw.o since it's just an internal process)
> Create script to partially automate Meza release process

- src/roles/saml/templates/config.php.j2
When TLS offloading, SSL load balancing, or reverse proxying, the `baseurlpath` value gets changed to only use `http` instead of `https.
Because the wiki auto redirect `http` to `https`, the issue isn't apparent to normal wiki usage. However, the issue arises when loading a wiki in an `iframe`. The `http` redirect by `simplesaml` causes a `Mixed Content` error. 
-  Adds `baseURL` to `application` property on config.
> Adds definition for baseURL

- src/roles/apache-php/tasks/profiling.yml
- src/roles/init-controller-config/tasks/main.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/parsoid/tasks/main.yml
- src/roles/saml/tasks/main.yml
- tests/deploys/setup-alt-source-backup.yml
* ~Move `ansible.cfg` setting `remote_tmp` out of `/tmp`~ (EDIT: not required, see first comment below)
* Set `TMPDIR` environment variable on Ansible Git module operations
* Closes #1149 
- None
> Support /tmp mounted with noexec

- src/roles/elasticsearch/tasks/main.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/parsoid/tasks/main.yml
- src/scripts/getmeza.sh
* Add `when: docker_skip_tasks is not defined or not docker_skip_tasks` to several tasks that can't run when building a docker image (e.g. starting services or any tasks relying upon a service)
* Fix `getmeza.sh` that had non-idempotency added since last docker build (over a year ago)
All builds failing
None
> Fix broken meza-docker-full image

- src/scripts/getmeza.sh
- src/scripts/meza.py
* Create lock file at start of `meza deploy` to prevent deploys when one is already underway
* None
> Prevent simultaneous deploys

- config/core/ansible.cfg
- src/roles/autodeployer/templates/check-for-changes.sh.j2
- src/scripts/meza.py
* Always show ansible colors (without this they don't show when written to a file)
* Add meza commands
* `meza deploy-check ENV` to check if a deploy is underway
* `meza deploy-lock ENV` and `meza deploy-unlock ENV` to add and remove lock file
* `meza deploy-kill ENV` to stop any deploy in progress (by autodeployer or in another terminal)
* `meza deploy-log ENV` to print the log file path for a deploy underway
* `meza deploy-tail ENV` to tail (view) the log of a deploy underway
* Autodeployer use `deploy-check`, `deploy-lock`, `deploy-unlock` to make sure a deploy is not running when it starts, and to block other deploys from starting while autodeployer prepares to deploy
* Add handling for SIGINT (ctrl-c pressed by user) since this could cause issues if lock file is not removed, but …
> Add several meza deploy-* commands supporting better deploys; add deploy log

- config/core/defaults.yml
- src/playbooks/site.yml
- src/roles/init-controller-config/tasks/main.yml
- src/scripts/getmeza.sh
* Make sure `/opt/meza` and public and secret configs have good permissions
* init-controller-config was being run on app-servers, but then had delegate:localhost on all tasks. This didn't make sense. Instead just run the play on localhost.
* Closes #800 
None
> Set ownership of meza and config; fix role:init-controller-config

- src/roles/backup-db-wikis/tasks/main.yml
- src/roles/backup-uploads/tasks/main.yml
- src/roles/nodejs/tasks/main.yml
* `ansible_distribution_version` no longer an ansible variable, get RedHat/CentOS version from `/etc/redhat-release`
* Ansible Synchronize module not working, use Meza rsync role
* None
- none
> Ansible 2.8 fixes

- src/roles/base/tasks/main.yml
- src/roles/mediawiki/tasks/main.yml
* Add EPEL repo package `python-pip` for PIP for Python 2.7
* Add IUS repo package `python35u-pip` for PIP for Python 3.5
* Add symlink for `pip3` so you don't have to do `pip3.5`
* Helps #809
- None
> Add PIP for Python 2 and 3

- src/roles/base/tasks/main.yml
Error was "yum lockfile is held by another process"
* Ensure `PackageKit` absent on RedHat
* None
- None
> Remove yum:PackageKit to remove error

- src/scripts/create-vm.sh
Use newline Internal Field Separator temporarily for selecting network adapter, then switch it back to spaces.
* Closes #1133
> Make net adapter select statement break on newlines

- src/roles/verify-wiki/tasks/main.yml
* Add `m_recursively_set_uploads_permissions` to do `chmod` and `chown` on `/opt/data-meza/uploads`. This can take a long time if you have lots of uploads, so generally speaking you don't want to do it. But the option exists in case something causes permissions to get improperly set. Generally this will only happen if using `meza push-backup <env>` to push uploads onto the server, so:
* Always do recursive permissions set when doing overwrite (in case pulling/pushing data changes permissions)
None
> Add option to recursively set perms on uploads dir

- src/roles/rsync-push/tasks/main.yml
* Does rsync push with `--no-perms` to avoid errors with not having permissions to `chmod` on the remote
* Adds a debug to help identify what wiki is being rsync'd
None
> Add --no-perms to rsync-push

- src/playbooks/site.yml
- src/scripts/meza.py
- tests/docker/import-from-alt-remote.setup.sh
These commits cherry-picked from 32.x branch. #1087 was the original PR.
* Remove forced (re)encryption of `secret.yml` on all deploys
* Remove initial encryption of `secret.yml` on `meza setup env`
* Remove `secret.yml` decryption in test `tests/docker/import-from-alt-remote.setup.sh`
* Add functions for encrypting/decrypting individual variables (recommended versus full file encryption):
* `meza maint encrypt_string <environment> <value-to-encrypt> <optional-var-name>`
* `meza maint decrypt_string <environment> <value-to-decrypt>`
Encrypting a value: `sudo meza maint encrypt_string <environment> supersecretpassword`
```
!vault |
$ANSIBLE_VAULT;1.1;AES256
61326233653335326662353765626565323363653033323664306332366163643236323238613466 …
```
> No force secret encrypt

- src/playbooks/push-backup.yml
- src/roles/autodeployer/templates/meza-autodeployer-cron.j2
- src/roles/backup-db-wikis-push/tasks/main.yml
- src/roles/backup-uploads-push/tasks/main.yml
Change settings for `meza push-backup <env>` from:
```yaml
backups_server_db_push:
addr: example.com
remote_user: meza-push-user
sql_files_path: /opt/data-meza/backups/YOURENVIRONMENT/<id>/
backups_server_uploads_push:
addr: example.com
remote_user: meza-push-user
uploads_dir_path: /opt/data-meza/uploads/<id>
```
to:
```yaml
push_backup:
crontime: "50 10 * * *"
remote_user: meza-push-user
short_name: "SOME NICE NAME"
db:
addr: example.com
path: /opt/data-meza/backups/vagrant/<id>/
uploads:
addr: example.com
path: /opt/data-meza/uploads/<id>
```
By adding `push_backup.crontime` this will automatically setup a cron job to run `meza push-backup <env>` periodically. This relies upon `autodeployer` also being setup.
None
> Make push-backup cron configurable; simplify push-backup settings

- config/core/defaults.yml
- src/playbooks/site.yml
- src/roles/haproxy/tasks/main.yml
- src/roles/init-controller-config/tasks/main.yml
- src/roles/setup-env/tasks/main.yml
- src/scripts/getmeza.sh
- src/scripts/meza.py
* Set `/opt/conf-meza/secret` and `/opt/conf-meza/secret/<env>` directory permissions to `775`. 
* Set `ssl/` directory to `775` as well, if it exists
* Set `secret.yml` and `hosts` files to `660`
N/A
> Standardize secret config permissions

- src/playbooks/delete-elasticsearch.yml
- src/playbooks/getdocker.yml
- src/roles/apache-php/tasks/ius.yml
- src/roles/apache-php/tasks/main.yml
- src/roles/apache-php/tasks/mssql_driver_for_php.yml
- src/roles/apache-php/tasks/php.yml
- src/roles/apache-php/tasks/profiling.yml
- src/roles/backup-config/tasks/main.yml
- src/roles/base-extras/tasks/main.yml
- src/roles/base/tasks/main.yml
- src/roles/database/tasks/setup-RedHat.yml
- src/roles/elasticsearch/tasks/es_upgrade.yml
- src/roles/elasticsearch/tasks/main.yml
- src/roles/gluster/tasks/setup-RedHat.yml
- src/roles/haproxy/tasks/main.yml
- src/roles/imagemagick/tasks/main.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/memcached/tasks/main.yml
- src/roles/nodejs/tasks/main.yml
- src/roles/nodejs/tasks/setup-RedHat.yml
- tests/deploys/setup-alt-source-backup.yml
* set `lock_timeout` on all `yum` and `package` tasks to avoid intermittent `yum lockfile is held by another process` failures, due to change in Ansible 2.8.
* Closes #1165 
* ansible/ansible#57189
- N/A
> Add lock_timeout to yum/package modules to fix Ansible 2.8 issue

- src/scripts/meza.py
No reason to have `meza setup dev-networking`. Just run `dev-networking.sh` directly to avoid issues with user input. 
* Closes #1169 
> Don't use 'meza' command for dev-networking

- src/playbooks/push-backup.yml
- src/roles/autodeployer/templates/meza-autodeployer-cron.j2
* 'notify' tag was mixed with 'never' tag, such that it seemed to make sense to do '--tags notify' to get it to notify. However, this would then skip over other things not tagged 'notify' like 'uploads' and 'db'. Instead you'd have to do '--tags db,uploads,anything-else-required'. Maybe '--tags all,notify' would work, but that's also confusing. Instead this commit removes the 'never' tag so notification will always happen. If a user wants to prevent notification they can do '--skip-tags notify'
* For some reason the list of servers to exclude on the push-backup playbook took the 32.x form with server groups like load-balancers-nonmeza. This missed load-balancers-unmanaged, the 31.x group naming.
None
None
> push-backup: Fix bad use of 'notify' tag; Add servers to exclude

- config/core/defaults.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/saml/tasks/main.yml
- src/roles/verify-wiki/tasks/import-wiki-sql.yml
On a recent installation several directories associated with Git or Composer installs were getting `750` or `640` permissions (zero for "others"). On previous installs these would get `755` or `644`. Umask is an obvious culprit but Meza should handle this. This pull request explicitly sets user/group/mode for various directories to remove the problem.
None
None
> Fixes for some servers setting zero "others" permissions

- src/roles/backup-db-wikis-push/tasks/main.yml
- src/roles/verify-wiki/tasks/main.yml
- src/roles/verify-wiki/tasks/transfer-backup-to-db-master.yml
Pushing backups from one server, then running deploy and trying to pick up those backups at a later time inevitably gets out of sync. For clarity, say PROD pushes to DEV. If PROD pushes, then another deploy happens on DEV, that deploy will _probably_ generate `.sql` files on DEV with a newer timestamp than those pushed from PROD. When a later deploy with `--overwrite` occurs it will not choose to use the one that was pushed, but instead choose the latest timestamp. This means DEV won't get the freshest data. In an even worse case, if DEV's database gets corrupted (as may happen on a dev server) then it may cause a situation where DEV can never get good data.
This change does three things:
1. Make `meza push-backup` write SQL files that look like `20190611120004_wiki_push.sql` instead of …
> Make pushed backups in form *push.sql and use them first; more debug

- src/roles/backups-cleanup/templates/backups-cleanup.sh.j2
Previously backups-cleanup gzipped all SQL backup files present. You don't always want this, particularly if you're sourcing from those backups. This PR allows specifying what should be gzipped. If no `backups_cleanup.gzip_rules` are specified, then nothing will be gzipped.
Previously you've been able to specify backups cleanup like:
```yaml
backups_cleanup:
crontime: "30 19 * * *"
removal_rules:
- "./*/$(date --date=\"2 days ago\" +\"%Y%m%d\")*.sql*"
- "./*/$(date --date=\"3 days ago\" +\"%Y%m%d\")*.sql*"
- "./*/$(date --date=\"4 days ago\" +\"%Y%m%d\")*.sql*"
```
Now you can add gzip rules:
```yaml
backups_cleanup:
crontime: "30 19 * * *"
removal_rules:
- "./*/$(date --date=\"4 days ago\" +\"%Y%m%d\")*.sql*"
- "./*/$(date --date=\"5 days ago\" +\"%Y%m%d\")*.sql*"
- "./*/$(date …
```
> Allow specifying rules for what to gzip in backups-cleanup

- src/roles/mediawiki/tasks/main.yml
- src/roles/mediawiki/templates/refresh-links.sh.j2
Adds refreshLinks.php script that breaks running into smaller parts to avoid PHP memory leaks as described in [1]
* None
There is no `meza` command for this so you have to manually envoke with either of these:
```bash
sudo bash /opt/.deploy-meza/refresh-links.sh
sudo bash /opt/.deploy-meza/refresh-links.sh someWikiID
```
[1] https://www.mediawiki.org/wiki/Manual:RefreshLinks.php#Chunking_refreshLinks.php_to_refresh_all_links_without_memory_leak
> Add refreshLinks script that handles memory leaks

- src/roles/mediawiki/tasks/main.yml
- src/roles/update.php/tasks/main.yml
- tests/docker/init-controller.sh
1. Do `composer install` and `composer update` of MW with `--no-dev` (via Ansible Composer module)
2. In CI tests 3 through 5 the `init-controller.sh` script is used. This was not mounting the Meza directory to the container, but was attempting to check out the the right version of Meza from this repository. This had two issues which were resolved by mounting:
1. It made it impossible to do local testing of that particular job without pushing the changes to this repository.
2. On travis PR jobs were getting the wrong version and thus were not getting necessary updates.
3. Not directly required for this PR but used in troubleshooting and generally useful: Make `update.php` role output update.php log and php error log on update.php failure
- Closes #1207 
None
> Add --no-dev to MW composer commands

- src/scripts/meza.py
Ultimately the web interface should allow admins to unlock the deploy lock file. This sets it up for the apache user to do that.
None
None
> Make meza-ansible:apache own deploy lock file, not root

- src/roles/saml/templates/config.php.j2
- src/roles/saml/templates/samlLocalSettings.php.j2
* `allow_skip_saml_users` now supports arrays of CIDR notation IP addresses.
Based on the current list of users in `allow_skip_saml_users` for `config-public/public.yml`, this shouldn't affect those users at all. All current users have `["*"]` set and as a result the added code from this pull request only affects user who would do something like `["192.0.2.0/24"]`. 
As of making this, no users do this and the only user account currently trying to is `RoundTableBot`.
> Cherry picks skip_saml CIDR notation support changes from 32.x

- config/core/MezaCoreExtensions.yml
Makes Extension:MezaExt track `master`. This is low-risk because the extension is entirely for Meza, All changes are currently for TransferPages or CI. This will help speed up development of TransferPages. After TransferPages is (more) stable this should be changed back to a new release tag.
None
None
> Make Extension:MezaExt track 'master' while TransferPages in development

- src/roles/saml/templates/config.php.j2
- src/roles/saml/templates/samlLocalSettings.php.j2
@GarrettGeorge I didn't realize that #1184 was merging into `31.x`. I should have changed it to `master` before I merged. This PR effectively does that.
Fixing my mistakes
> Take 3: skip_saml CIDR notation support changes

- config/core/defaults.yml
- src/roles/mediawiki/templates/composer.local.json.j2
* Bump MW to 1.31.2
* Remove `pear/net_smtp` from Meza since it's included within MediaWiki's `composer.json` now.
* Closes #1210
None
> Bump MW to 1.31.2; remove pear/net_smtp from meza (part of MW now)

- src/scripts/meza.py
#1208 set group `apache` for the deploy lock file. This is great for future ability to unlock the deploy via the web interface, but unfortunately it makes it impossible to deploy initially since group `apache` doesn't exist initially. This PR adds a check for whether the apache group exists, and if not it sets the group to `wheel`.
* Closes #1216
None
> Check if apache group exists before setting as group for lock file

- src/roles/mediawiki/tasks/main.yml
Allow specifying `refspec` to mediawiki git repos. This will allow specifying in-work gerrit patches for extensions, skins, and mediawiki core. For example:
```yaml
- name: PageForms
repo: "https://gerrit.wikimedia.org/r/mediawiki/extensions/PageForms.git"
version: "ad2e9469504e21df001e5160194b5a82847dc845"
refspec: "refs/changes/03/518403/15"
```
Unfortunately it seems you need the hash of the gerrit patch, and can't track the latest commit. When you're on a Gerrit page like [this one](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/VisualEditor/+/528893), you can get the hash here:
* Closes #1024
> Allow specifying refspec in MW git repos

- config/core/defaults.yml
- src/roles/apache-php/templates/php.ini.j2
Allow specifying `php_max_upload_filesize` in config which sets `php.ini` variables `upload_max_filesize` and `post_max_size`. Example below would set the PHP max file upload size to 300 MB. This would be added to `public.yml`.
```yaml
php_max_upload_filesize: "300M"
```
None
> Allow specifying PHP max upload size in config

- config/core/MezaCoreExtensions.yml
https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/DataTransfer/+/730cbfbcc7cc255724eaceb76a3abc6fcc9c93aa
* Changed DataTransfer version from "{{ mediawiki_default_branch }}" to "730cbfbcc7cc255724eaceb76a3abc6fcc9c93aa"
* Addresses the DataTransfer bug that replaces all multiple-instance templates on pages imported with the phrase "Array"
> Updating Data Transfer to fix import bug

- config/core/defaults.yml
- src/roles/apache-php/tasks/main.yml
Apache cannot write to /opt/data-meza/tmp. For Special:TransferPages, it is necessary for Apache to write a temp file, which then is picked up by the MW job queue and executed as user meza-ansible.
* Add `/opt/data-meza/mw-temp`
* Add `m_paths` to `defaults.yml` to start using better method of maintaining all paths
* None
> Add /opt/data-meza/mw-temp that apache can modify

- src/scripts/getmeza.sh
* Add `checkInternetConnection` function to wait for Internet connection in getmeza script.
* Addresses #1231
Vagrant or getmeza script needs to check Internet connectivity of guest before proceeding #1231:
https://github.com/enterprisemediawiki/meza/issues/1231
```
Could not connect to mirrorlist.centos.org. Internet connection might be down. Retrying (#100) in 3 seconds...
...
Could not connect to mirrorlist.centos.org. Internet connection might be down. Retrying (#1) in 3 seconds...
Meza has been trying to install but hasn't found an internet connection for 5 minutes. Verify internet connectivity and try again.
```
> Add function to wait for Internet connection in getmeza script.

- config/core/defaults.yml
- src/roles/base/tasks/main.yml
- src/roles/firewalld/handlers/main.yml
- src/roles/firewalld/tasks/main.yml
- src/roles/haproxy/tasks/main.yml
- src/roles/nodejs/tasks/setup-RedHat.yml
- src/roles/saml/tasks/main.yml
- src/scripts/meza.py
- tests/deploys/backup-to-remote.controller.sh
- tests/deploys/import-from-remote.controller.sh
- tests/deploys/monolith-from-import.controller.sh
- tests/deploys/monolith-from-scratch.controller.sh
- tests/docker/import-from-alt-remote.setup.sh
- tests/docker/import-from-remote.setup.sh
- tests/docker/init-container.sh
Two problems stacked causing tests to fail.
* Problem 1: Something changed about Travis. Either the version of Docker used, or perhaps some configuration. Root cause has yet to be determined. The problem was narrowed to firewall commands, which really shouldn't be run on containers in the first place. To address this, the variable `firewall_skip_tasks` is checked for on firewall tasks. If it is set to `True` then those tasks are skipped. Additionally, the `--no-firewall` option is added to `deploy` to trigger this setting (or it can be added in config). Travis tests all run `meza deploy --no-firewall` now. 
* Problem 2: Fixing problem 1 uncovered problem 2, which was also reported in #1235. The problem here appears to be due to some changes in Parsoid dependencies. Upgrading from Parsoid …
> Make builds pass again; fix #1235 and #1237

- config/core/MezaCoreExtensions.yml
* Updating PageForms from:730390a31a56c001af83948af1eefc5174abbe06
to: bb1beb015f0a16db10d96c895dfadf9eb691834d
* Add calendar interface to Page Forms
> Add a calendar interface to Page Forms

- src/roles/apache-php/tasks/php.yml
By using a wildcard match we can ensure that all versions of php 5.x are removed from the system.
remove the long list of items and use glob instead
This is intended to fix situations where tests are failing because PHP 5.4 packages are found on the system.
> Remove all 5.x php packages

- src/roles/apache-php/tasks/ius.yml
Hi,
Today my `meza deploy` failed with the following error:
```
TASK [apache-php : Install IUS (RHEL) repo.] ***************************************************************************************************************************
Monday 01 June 2020  15:20:00 +1000 (0:00:00.051)       0:03:33.396 ***********
fatal: [localhost]: FAILED! => {
"changed": false
}
MSG:
Failed to get nevra information from RPM package: https://rhel7.iuscommunity.org/ius-release.rpm
```
Browsing to the URL above refers to their issue https://github.com/iusrepo/announce/issues/18. It appears as though the URLs currently used in the meza playbooks were deprecated redirects.
* Updates URL to RPM hosted by IUS
* There was previously different links for RHEL and CentOS, but they seem to have converged
No open …
> Update URL to IUS RPM

- RELEASE-NOTES.md
Update PHP to 7.2, fix IUS repo, fix Python symlink
* bbe0009 Remove symlink creation for pip3; IUS appears to do that automatically now
* c50be32 Remove mcrypt extension no longer available after PHP 7.1
* 01c04bb Bump to PHP 7.2
* 10bc863 Fix typo (backslash)
* f701201 Add second IUS repo and GPG key
* 8e47150 Update URL to IUS RPM See https://github.com/iusrepo/announce/issues/18
* 44f2d2c Python 2/3 compatibility
* 6	James Montalvo
* 1	Andrew Foster
* 1	Daren Welsh
* 1	Greg Rundlett
> 31.10.0 release

- src/roles/apache-php/tasks/mssql_driver_for_php.yml
Fix for the following error if using MSFT SQL add-on (for external MSSQL databases, not for wiki):
```
TASK [apache-php : Install sqlsrv and pdo_sqlsrv PECL packages] ****************
Friday 05 June 2020  16:02:48 -0500 (0:00:06.179)       0:02:28.082 ***********
failed: [localhost] (item=pecl/sqlsrv) => {
"ansible_loop_var": "item",
"changed": false,
"item": "pecl/sqlsrv"
}
MSG:
failed to install pecl/sqlsrv: WARNING: channel "pecl.php.net" has updated its protocols, use "pear channel-update pecl.php.net" to update
```
None
- None
> Ensure PEAR channel up-to-date

- config/core/defaults.yml
- src/roles/base/tasks/main.yml
* Added config variable `use_ntp` to config/core/defaults.yml
* Added `when: use_ntp` to "tasks" involving ntp to src/roles/base/tasks/main.yml
* Collaborated with James to help fix server time issue
> Added config variable use_ntp

- src/roles/composer/tasks/main.yml
The `31.x` branch got out of sync with `master` yesterday to support a quick fix (9630b3015c876f9d6073d7999df81a6a177119a1) to get Composer to work.
This change merges that 31.x hotfix back into master.
* Closes ##1272
None
> Resync master and 31.x

- config/core/defaults.yml
* MediaWiki to latest 1.31.x version
None
None
> Bump MW to 1.31.12

- vagrantconf.default.yml
* In `vagrantconf.default.yml` set the default RAM to 4GB. Meza fails with 2GB.
* None
> Bump base Vagrant RAM from 2GB to 4GB

- RELEASE-NOTES.md
Testing fixes, Add LDAP module, Bump MW to 1.31.12
* e05ea12 Bump base Vagrant RAM from 2GB to 4GB, else problems (#1278)
* 908ac75 Bump MW to 1.31.12 (#1277)
* 2380aa2 Enforce Composer 1.x version (#1275)
* 8b5c112 Added config variable use_ntp (#1271)
* 4160ae3 Bump MediaWiki to 1.31.7 (#1267)
* 65aa596 add ldap module (#1261)
* 591df68 Point tests to new Docker images built from this repo; only run build process on commits to master
* 8a22485 Remove secret.yml encryption per #1175
* 57e8469 Need --skip-conn-check on getmeza.sh within docker; temporarily skip other builds
* 11dc3e8 Make Dockerfiles pull FROM correct base image
* f01ae65 Add later test images
* 62886be Build test container 'base' on pushes to 'docker-build' branch
* b5ce5e3 GitHub Actions fail-fast-->false, to prevent …
> 31.12.0 release

- RELEASE-NOTES.md
- src/roles/backups-cleanup/templates/backups-cleanup.sh.j2
Add new backups-cleanup method
* bba5624 Add backups cleanup that goes into each wiki dir for better cleanup options
Allows new config like:
```yaml
#
#
backups_cleanup:
crontime: "0 * * * *"
removal_rules_each_wiki:
- "rm $(ls -F *_wiki.sql | head -n -1) -f"
- "rm $(ls -F *_wiki_push.sql | head -n -1) -f"
```
This will keep the `/opt/data-meza/backups/<environment name>/<wiki id>` clean, with only the latest `*_wiki.sql` and `*_wiki_push.sql` files.
> 31.13.0 release

- RELEASE-NOTES.md
Bump SMW and SRF to latest
* 7bcb1f2 Fix typo in do-release.sh (#1284)
* 48b8a3a Fix: improve do-release.sh, iss #1173 (#1283)
* 17502cd SMW 3.2.2 and SRF 3.2.0 (#1282)
* 2	James Montalvo
* 1	Daren Welsh
```bash
sudo meza update 31.14.0
sudo meza deploy <insert-your-environment-name>
```
> 31.14.0 release

- .github/workflows/test.yml
- .travis.yml
* Removes the "backup" tests from GitHub actions
* Makes the "backup" tests allowed to fail in Travis CI
Backup tests aren't testing deploy capability, but pushing data from server to server. This capability could be tested before, but has stopped working in test environments despite working in real environments, and time is not available to fix the infrastructure issues.
None
None
> Only require the main tests, not the backups tests with infra failures

- config/core/MezaCoreExtensions.yml
* Update SemanticCompoundQueries to 2.1.0
* Previous version (1.2.0) was not compatible with MW, SMW, and PHP
> SemanticCompoundQueries update to 2.1.0

- src/roles/apache-php/tasks/mssql_driver_for_php.yml
Workaround for not-really-failing-but-acting-like-it's-failing installs of MS SQL Server drivers for PHP. This workaround is not ideal (uses `ignore_errors), so #1298 was created to track making it better in the future.
> fix(pecl): make pecl packages not fail unnecessarily

- RELEASE-NOTES.md
Deploy fixes: PECL, SimpleSamlPhp
* 5b8a3e4 fix(pecl): make pecl packages not fail unnecessarily
* 0f772bc chore(vagrant): bump vagrant box from bento/centos-7.4 to 7.9
* eb47c64 fix(saml): ensure SimpleSamlPhp actually installs
* f680a39 Fix: get simplesamlphp via tarball so later versions work; bump version
* James Montalvo
```bash
sudo meza update 31.17.0
sudo meza deploy <insert-your-environment-name>
```
> 31.17.0 release
